using BlogApp.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace BlogApp.Repository.Database
{
    public class BlogDbContext : DbContext
    {
        public BlogDbContext()
        {
            Database.EnsureCreated();
        }

        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder
                    .UseLazyLoadingProxies()
                    .UseInMemoryDatabase("blogs");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Post>(post => post
                .HasOne(post => post.Blog)
                .WithMany(blog => blog.Posts)
                .HasForeignKey(post => post.BlogId)
                .OnDelete(DeleteBehavior.Cascade));

            modelBuilder.Entity<Comment>(comment => comment
                .HasOne(comment => comment.Post)
                .WithMany(post => post.Comments)
                .HasForeignKey(comment => comment.PostId)
                .OnDelete(DeleteBehavior.Cascade)
            );

            List<Blog> blogs = new List<Blog>()
            {
                new Blog() { Id = 1, BlogName = "blog1"},
                new Blog() { Id = 2, BlogName = "blog2"},
                new Blog() { Id = 3, BlogName = "blog3"},
                new Blog() { Id = 4, BlogName = "blog4"},
                new Blog() { Id = 5, BlogName = "blog5"},
                new Blog() { Id = 6, BlogName = "blog6"},
                new Blog() { Id = 7, BlogName = "blog7"},
                new Blog() { Id = 8, BlogName = "blog8"},
                new Blog() { Id = 9, BlogName = "blog9"},
                new Blog() { Id = 10, BlogName = "blog10"}
            };

            List<Post> posts = new List<Post>()
            {
                new Post(){ Id = 1, PostAuthor = "author18", Content = "[author18 post's]", BlogId = 5, Category = "Education"},
                new Post(){ Id = 2, PostAuthor = "author1", Content = "[author1 post's]", BlogId = 5, Category = "Health"},
                new Post(){ Id = 3, PostAuthor = "author14", Content = "[author14 post's]", BlogId = 4, Category = "Education"},
                new Post(){ Id = 4, PostAuthor = "author4", Content = "[author4 post's]", BlogId = 10, Category = "Photography"},
                new Post(){ Id = 5, PostAuthor = "author25", Content = "[author25 post's]", BlogId = 5, Category = "Lifestyle"},
                new Post(){ Id = 6, PostAuthor = "author27", Content = "[author27 post's]", BlogId = 5, Category = "Science"},
                new Post(){ Id = 7, PostAuthor = "author15", Content = "[author15 post's]", BlogId = 8, Category = "Parenting"},
                new Post(){ Id = 8, PostAuthor = "author25", Content = "[author25 post's]", BlogId = 1, Category = "Parenting"},
                new Post(){ Id = 9, PostAuthor = "author7", Content = "[author7 post's]", BlogId = 7, Category = "Travel"},
                new Post(){ Id = 10, PostAuthor = "author6", Content = "[author6 post's]", BlogId = 1, Category = "DIY"},
                new Post(){ Id = 11, PostAuthor = "author13", Content = "[author13 post's]", BlogId = 1, Category = "DIY"},
                new Post(){ Id = 12, PostAuthor = "author13", Content = "[author13 post's]", BlogId = 7, Category = "Books"},
                new Post(){ Id = 13, PostAuthor = "author25", Content = "[author25 post's]", BlogId = 7, Category = "Lifestyle"},
                new Post(){ Id = 14, PostAuthor = "author29", Content = "[author29 post's]", BlogId = 6, Category = "Business"},
                new Post(){ Id = 15, PostAuthor = "author3", Content = "[author3 post's]", BlogId = 7, Category = "Fitness"},
                new Post(){ Id = 16, PostAuthor = "author5", Content = "[author5 post's]", BlogId = 10, Category = "Entertainment"},
                new Post(){ Id = 17, PostAuthor = "author8", Content = "[author8 post's]", BlogId = 4, Category = "DIY"},
                new Post(){ Id = 18, PostAuthor = "author2", Content = "[author2 post's]", BlogId = 5, Category = "Finance"},
                new Post(){ Id = 19, PostAuthor = "author18", Content = "[author18 post's]", BlogId = 3, Category = "Food"},
                new Post(){ Id = 20, PostAuthor = "author8", Content = "[author8 post's]", BlogId = 5, Category = "Music"},
                new Post(){ Id = 21, PostAuthor = "author28", Content = "[author28 post's]", BlogId = 3, Category = "DIY"},
                new Post(){ Id = 22, PostAuthor = "author10", Content = "[author10 post's]", BlogId = 6, Category = "Gaming"},
                new Post(){ Id = 23, PostAuthor = "author1", Content = "[author1 post's]", BlogId = 3, Category = "DIY"},
                new Post(){ Id = 24, PostAuthor = "author10", Content = "[author10 post's]", BlogId = 10, Category = "Art"},
                new Post(){ Id = 25, PostAuthor = "author9", Content = "[author9 post's]", BlogId = 8, Category = "Science"},
                new Post(){ Id = 26, PostAuthor = "author4", Content = "[author4 post's]", BlogId = 9, Category = "Technology"},
                new Post(){ Id = 27, PostAuthor = "author15", Content = "[author15 post's]", BlogId = 5, Category = "Food"},
                new Post(){ Id = 28, PostAuthor = "author5", Content = "[author5 post's]", BlogId = 6, Category = "Technology"},
                new Post(){ Id = 29, PostAuthor = "author7", Content = "[author7 post's]", BlogId = 5, Category = "Fashion"},
                new Post(){ Id = 30, PostAuthor = "author20", Content = "[author20 post's]", BlogId = 3, Category = "DIY"},
                new Post(){ Id = 31, PostAuthor = "author9", Content = "[author9 post's]", BlogId = 8, Category = "Books"},
                new Post(){ Id = 32, PostAuthor = "author16", Content = "[author16 post's]", BlogId = 4, Category = "Fashion"},
                new Post(){ Id = 33, PostAuthor = "author6", Content = "[author6 post's]", BlogId = 2, Category = "Art"},
                new Post(){ Id = 34, PostAuthor = "author19", Content = "[author19 post's]", BlogId = 5, Category = "Fitness"},
                new Post(){ Id = 35, PostAuthor = "author6", Content = "[author6 post's]", BlogId = 6, Category = "Gaming"},
                new Post(){ Id = 36, PostAuthor = "author5", Content = "[author5 post's]", BlogId = 2, Category = "Travel"},
                new Post(){ Id = 37, PostAuthor = "author16", Content = "[author16 post's]", BlogId = 7, Category = "Education"},
                new Post(){ Id = 38, PostAuthor = "author26", Content = "[author26 post's]", BlogId = 5, Category = "Finance"},
                new Post(){ Id = 39, PostAuthor = "author5", Content = "[author5 post's]", BlogId = 6, Category = "Lifestyle"},
                new Post(){ Id = 40, PostAuthor = "author29", Content = "[author29 post's]", BlogId = 8, Category = "Fashion"},
                new Post(){ Id = 41, PostAuthor = "author27", Content = "[author27 post's]", BlogId = 8, Category = "Food"},
                new Post(){ Id = 42, PostAuthor = "author6", Content = "[author6 post's]", BlogId = 3, Category = "Business"},
                new Post(){ Id = 43, PostAuthor = "author24", Content = "[author24 post's]", BlogId = 9, Category = "Books"},
                new Post(){ Id = 44, PostAuthor = "author27", Content = "[author27 post's]", BlogId = 10, Category = "Lifestyle"},
                new Post(){ Id = 45, PostAuthor = "author24", Content = "[author24 post's]", BlogId = 5, Category = "Health"},
                new Post(){ Id = 46, PostAuthor = "author5", Content = "[author5 post's]", BlogId = 2, Category = "Entertainment"},
                new Post(){ Id = 47, PostAuthor = "author29", Content = "[author29 post's]", BlogId = 8, Category = "DIY"},
                new Post(){ Id = 48, PostAuthor = "author7", Content = "[author7 post's]", BlogId = 3, Category = "Parenting"},
                new Post(){ Id = 49, PostAuthor = "author5", Content = "[author5 post's]", BlogId = 4, Category = "Gaming"},
                new Post(){ Id = 50, PostAuthor = "author10", Content = "[author10 post's]", BlogId = 3, Category = "Books"},
                new Post(){ Id = 51, PostAuthor = "author22", Content = "[author22 post's]", BlogId = 7, Category = "Health"},
                new Post(){ Id = 52, PostAuthor = "author19", Content = "[author19 post's]", BlogId = 7, Category = "DIY"},
                new Post(){ Id = 53, PostAuthor = "author25", Content = "[author25 post's]", BlogId = 2, Category = "Fashion"},
                new Post(){ Id = 54, PostAuthor = "author12", Content = "[author12 post's]", BlogId = 9, Category = "Photography"},
                new Post(){ Id = 55, PostAuthor = "author3", Content = "[author3 post's]", BlogId = 3, Category = "Gaming"},
                new Post(){ Id = 56, PostAuthor = "author19", Content = "[author19 post's]", BlogId = 6, Category = "Finance"},
                new Post(){ Id = 57, PostAuthor = "author24", Content = "[author24 post's]", BlogId = 5, Category = "Travel"},
                new Post(){ Id = 58, PostAuthor = "author19", Content = "[author19 post's]", BlogId = 5, Category = "Science"},
                new Post(){ Id = 59, PostAuthor = "author12", Content = "[author12 post's]", BlogId = 1, Category = "Parenting"},
                new Post(){ Id = 60, PostAuthor = "author16", Content = "[author16 post's]", BlogId = 2, Category = "Entertainment"}
            };

            List<Comment> comments = new List<Comment>()
            {
                new Comment(){ Id = 1, UserName = "user553", Content = "[user553 comment's about author18 post's]", PostId = 1, PostRating = 1},
                new Comment(){ Id = 2, UserName = "user316", Content = "[user316 comment's about author18 post's]", PostId = 1, PostRating = 1},
                new Comment(){ Id = 3, UserName = "user233", Content = "[user233 comment's about author18 post's]", PostId = 1, PostRating = 9},
                new Comment(){ Id = 4, UserName = "user654", Content = "[user654 comment's about author18 post's]", PostId = 1, PostRating = 5},
                new Comment(){ Id = 5, UserName = "user643", Content = "[user643 comment's about author18 post's]", PostId = 1, PostRating = 1},
                new Comment(){ Id = 6, UserName = "user284", Content = "[user284 comment's about author18 post's]", PostId = 1, PostRating = 2},
                new Comment(){ Id = 7, UserName = "user302", Content = "[user302 comment's about author1 post's]", PostId = 2, PostRating = 9},
                new Comment(){ Id = 8, UserName = "user203", Content = "[user203 comment's about author1 post's]", PostId = 2, PostRating = 6},
                new Comment(){ Id = 9, UserName = "user282", Content = "[user282 comment's about author1 post's]", PostId = 2, PostRating = 8},
                new Comment(){ Id = 10, UserName = "user524", Content = "[user524 comment's about author1 post's]", PostId = 2, PostRating = 2},
                new Comment(){ Id = 11, UserName = "user693", Content = "[user693 comment's about author1 post's]", PostId = 2, PostRating = 4},
                new Comment(){ Id = 12, UserName = "user365", Content = "[user365 comment's about author1 post's]", PostId = 2, PostRating = 5},
                new Comment(){ Id = 13, UserName = "user209", Content = "[user209 comment's about author1 post's]", PostId = 2, PostRating = 4},
                new Comment(){ Id = 14, UserName = "user431", Content = "[user431 comment's about author1 post's]", PostId = 2, PostRating = 8},
                new Comment(){ Id = 15, UserName = "user117", Content = "[user117 comment's about author1 post's]", PostId = 2, PostRating = 7},
                new Comment(){ Id = 16, UserName = "user56", Content = "[user56 comment's about author14 post's]", PostId = 3, PostRating = 1},
                new Comment(){ Id = 17, UserName = "user448", Content = "[user448 comment's about author14 post's]", PostId = 3, PostRating = 6},
                new Comment(){ Id = 18, UserName = "user610", Content = "[user610 comment's about author14 post's]", PostId = 3, PostRating = 1},
                new Comment(){ Id = 19, UserName = "user401", Content = "[user401 comment's about author14 post's]", PostId = 3, PostRating = 3},
                new Comment(){ Id = 20, UserName = "user535", Content = "[user535 comment's about author14 post's]", PostId = 3, PostRating = 4},
                new Comment(){ Id = 21, UserName = "user109", Content = "[user109 comment's about author14 post's]", PostId = 3, PostRating = 4},
                new Comment(){ Id = 22, UserName = "user509", Content = "[user509 comment's about author14 post's]", PostId = 3, PostRating = 6},
                new Comment(){ Id = 23, UserName = "user212", Content = "[user212 comment's about author14 post's]", PostId = 3, PostRating = 7},
                new Comment(){ Id = 24, UserName = "user571", Content = "[user571 comment's about author14 post's]", PostId = 3, PostRating = 2},
                new Comment(){ Id = 25, UserName = "user316", Content = "[user316 comment's about author4 post's]", PostId = 4, PostRating = 2},
                new Comment(){ Id = 26, UserName = "user155", Content = "[user155 comment's about author4 post's]", PostId = 4, PostRating = 6},
                new Comment(){ Id = 27, UserName = "user587", Content = "[user587 comment's about author4 post's]", PostId = 4, PostRating = 1},
                new Comment(){ Id = 28, UserName = "user431", Content = "[user431 comment's about author4 post's]", PostId = 4, PostRating = 5},
                new Comment(){ Id = 29, UserName = "user152", Content = "[user152 comment's about author25 post's]", PostId = 5, PostRating = 8},
                new Comment(){ Id = 30, UserName = "user645", Content = "[user645 comment's about author25 post's]", PostId = 5, PostRating = 8},
                new Comment(){ Id = 31, UserName = "user645", Content = "[user645 comment's about author25 post's]", PostId = 5, PostRating = 9},
                new Comment(){ Id = 32, UserName = "user204", Content = "[user204 comment's about author25 post's]", PostId = 5, PostRating = 5},
                new Comment(){ Id = 33, UserName = "user390", Content = "[user390 comment's about author25 post's]", PostId = 5, PostRating = 2},
                new Comment(){ Id = 34, UserName = "user111", Content = "[user111 comment's about author25 post's]", PostId = 5, PostRating = 4},
                new Comment(){ Id = 35, UserName = "user615", Content = "[user615 comment's about author25 post's]", PostId = 5, PostRating = 1},
                new Comment(){ Id = 36, UserName = "user233", Content = "[user233 comment's about author25 post's]", PostId = 5, PostRating = 7},
                new Comment(){ Id = 37, UserName = "user410", Content = "[user410 comment's about author25 post's]", PostId = 5, PostRating = 6},
                new Comment(){ Id = 38, UserName = "user74", Content = "[user74 comment's about author25 post's]", PostId = 5, PostRating = 9},
                new Comment(){ Id = 39, UserName = "user139", Content = "[user139 comment's about author27 post's]", PostId = 6, PostRating = 3},
                new Comment(){ Id = 40, UserName = "user610", Content = "[user610 comment's about author27 post's]", PostId = 6, PostRating = 2},
                new Comment(){ Id = 41, UserName = "user207", Content = "[user207 comment's about author27 post's]", PostId = 6, PostRating = 4},
                new Comment(){ Id = 42, UserName = "user284", Content = "[user284 comment's about author27 post's]", PostId = 6, PostRating = 3},
                new Comment(){ Id = 43, UserName = "user446", Content = "[user446 comment's about author15 post's]", PostId = 7, PostRating = 2},
                new Comment(){ Id = 44, UserName = "user234", Content = "[user234 comment's about author15 post's]", PostId = 7, PostRating = 6},
                new Comment(){ Id = 45, UserName = "user113", Content = "[user113 comment's about author15 post's]", PostId = 7, PostRating = 2},
                new Comment(){ Id = 46, UserName = "user138", Content = "[user138 comment's about author15 post's]", PostId = 7, PostRating = 9},
                new Comment(){ Id = 47, UserName = "user56", Content = "[user56 comment's about author15 post's]", PostId = 7, PostRating = 5},
                new Comment(){ Id = 48, UserName = "user84", Content = "[user84 comment's about author15 post's]", PostId = 7, PostRating = 4},
                new Comment(){ Id = 49, UserName = "user103", Content = "[user103 comment's about author15 post's]", PostId = 7, PostRating = 4},
                new Comment(){ Id = 50, UserName = "user418", Content = "[user418 comment's about author15 post's]", PostId = 7, PostRating = 5},
                new Comment(){ Id = 51, UserName = "user115", Content = "[user115 comment's about author25 post's]", PostId = 8, PostRating = 5},
                new Comment(){ Id = 52, UserName = "user692", Content = "[user692 comment's about author25 post's]", PostId = 8, PostRating = 2},
                new Comment(){ Id = 53, UserName = "user440", Content = "[user440 comment's about author25 post's]", PostId = 8, PostRating = 7},
                new Comment(){ Id = 54, UserName = "user155", Content = "[user155 comment's about author25 post's]", PostId = 8, PostRating = 4},
                new Comment(){ Id = 55, UserName = "user201", Content = "[user201 comment's about author25 post's]", PostId = 8, PostRating = 2},
                new Comment(){ Id = 56, UserName = "user695", Content = "[user695 comment's about author25 post's]", PostId = 8, PostRating = 7},
                new Comment(){ Id = 57, UserName = "user301", Content = "[user301 comment's about author25 post's]", PostId = 8, PostRating = 8},
                new Comment(){ Id = 58, UserName = "user346", Content = "[user346 comment's about author7 post's]", PostId = 9, PostRating = 7},
                new Comment(){ Id = 59, UserName = "user512", Content = "[user512 comment's about author7 post's]", PostId = 9, PostRating = 4},
                new Comment(){ Id = 60, UserName = "user468", Content = "[user468 comment's about author7 post's]", PostId = 9, PostRating = 9},
                new Comment(){ Id = 61, UserName = "user128", Content = "[user128 comment's about author7 post's]", PostId = 9, PostRating = 8},
                new Comment(){ Id = 62, UserName = "user674", Content = "[user674 comment's about author7 post's]", PostId = 9, PostRating = 7},
                new Comment(){ Id = 63, UserName = "user666", Content = "[user666 comment's about author7 post's]", PostId = 9, PostRating = 6},
                new Comment(){ Id = 64, UserName = "user426", Content = "[user426 comment's about author6 post's]", PostId = 10, PostRating = 1},
                new Comment(){ Id = 65, UserName = "user292", Content = "[user292 comment's about author6 post's]", PostId = 10, PostRating = 5},
                new Comment(){ Id = 66, UserName = "user68", Content = "[user68 comment's about author6 post's]", PostId = 10, PostRating = 3},
                new Comment(){ Id = 67, UserName = "user627", Content = "[user627 comment's about author6 post's]", PostId = 10, PostRating = 1},
                new Comment(){ Id = 68, UserName = "user521", Content = "[user521 comment's about author6 post's]", PostId = 10, PostRating = 8},
                new Comment(){ Id = 69, UserName = "user52", Content = "[user52 comment's about author6 post's]", PostId = 10, PostRating = 5},
                new Comment(){ Id = 70, UserName = "user552", Content = "[user552 comment's about author6 post's]", PostId = 10, PostRating = 3},
                new Comment(){ Id = 71, UserName = "user67", Content = "[user67 comment's about author6 post's]", PostId = 10, PostRating = 7},
                new Comment(){ Id = 72, UserName = "user578", Content = "[user578 comment's about author6 post's]", PostId = 10, PostRating = 7},
                new Comment(){ Id = 73, UserName = "user637", Content = "[user637 comment's about author6 post's]", PostId = 10, PostRating = 5},
                new Comment(){ Id = 74, UserName = "user129", Content = "[user129 comment's about author13 post's]", PostId = 11, PostRating = 9},
                new Comment(){ Id = 75, UserName = "user65", Content = "[user65 comment's about author13 post's]", PostId = 11, PostRating = 9},
                new Comment(){ Id = 76, UserName = "user678", Content = "[user678 comment's about author13 post's]", PostId = 11, PostRating = 5},
                new Comment(){ Id = 77, UserName = "user655", Content = "[user655 comment's about author13 post's]", PostId = 11, PostRating = 9},
                new Comment(){ Id = 78, UserName = "user681", Content = "[user681 comment's about author13 post's]", PostId = 11, PostRating = 7},
                new Comment(){ Id = 79, UserName = "user431", Content = "[user431 comment's about author13 post's]", PostId = 11, PostRating = 7},
                new Comment(){ Id = 80, UserName = "user219", Content = "[user219 comment's about author13 post's]", PostId = 11, PostRating = 5},
                new Comment(){ Id = 81, UserName = "user409", Content = "[user409 comment's about author13 post's]", PostId = 11, PostRating = 4},
                new Comment(){ Id = 82, UserName = "user413", Content = "[user413 comment's about author13 post's]", PostId = 11, PostRating = 8},
                new Comment(){ Id = 83, UserName = "user131", Content = "[user131 comment's about author13 post's]", PostId = 11, PostRating = 8},
                new Comment(){ Id = 84, UserName = "user338", Content = "[user338 comment's about author13 post's]", PostId = 11, PostRating = 1},
                new Comment(){ Id = 85, UserName = "user333", Content = "[user333 comment's about author13 post's]", PostId = 12, PostRating = 7},
                new Comment(){ Id = 86, UserName = "user245", Content = "[user245 comment's about author13 post's]", PostId = 12, PostRating = 1},
                new Comment(){ Id = 87, UserName = "user536", Content = "[user536 comment's about author13 post's]", PostId = 12, PostRating = 1},
                new Comment(){ Id = 88, UserName = "user502", Content = "[user502 comment's about author13 post's]", PostId = 12, PostRating = 2},
                new Comment(){ Id = 89, UserName = "user619", Content = "[user619 comment's about author13 post's]", PostId = 12, PostRating = 3},
                new Comment(){ Id = 90, UserName = "user544", Content = "[user544 comment's about author13 post's]", PostId = 12, PostRating = 3},
                new Comment(){ Id = 91, UserName = "user419", Content = "[user419 comment's about author13 post's]", PostId = 12, PostRating = 6},
                new Comment(){ Id = 92, UserName = "user351", Content = "[user351 comment's about author13 post's]", PostId = 12, PostRating = 2},
                new Comment(){ Id = 93, UserName = "user600", Content = "[user600 comment's about author25 post's]", PostId = 13, PostRating = 2},
                new Comment(){ Id = 94, UserName = "user68", Content = "[user68 comment's about author25 post's]", PostId = 13, PostRating = 8},
                new Comment(){ Id = 95, UserName = "user245", Content = "[user245 comment's about author25 post's]", PostId = 13, PostRating = 7},
                new Comment(){ Id = 96, UserName = "user212", Content = "[user212 comment's about author25 post's]", PostId = 13, PostRating = 7},
                new Comment(){ Id = 97, UserName = "user462", Content = "[user462 comment's about author25 post's]", PostId = 13, PostRating = 4},
                new Comment(){ Id = 98, UserName = "user117", Content = "[user117 comment's about author25 post's]", PostId = 13, PostRating = 6},
                new Comment(){ Id = 99, UserName = "user669", Content = "[user669 comment's about author25 post's]", PostId = 13, PostRating = 6},
                new Comment(){ Id = 100, UserName = "user247", Content = "[user247 comment's about author25 post's]", PostId = 13, PostRating = 2},
                new Comment(){ Id = 101, UserName = "user121", Content = "[user121 comment's about author25 post's]", PostId = 13, PostRating = 9},
                new Comment(){ Id = 102, UserName = "user296", Content = "[user296 comment's about author29 post's]", PostId = 14, PostRating = 4},
                new Comment(){ Id = 103, UserName = "user202", Content = "[user202 comment's about author29 post's]", PostId = 14, PostRating = 1},
                new Comment(){ Id = 104, UserName = "user142", Content = "[user142 comment's about author29 post's]", PostId = 14, PostRating = 7},
                new Comment(){ Id = 105, UserName = "user688", Content = "[user688 comment's about author29 post's]", PostId = 14, PostRating = 2},
                new Comment(){ Id = 106, UserName = "user78", Content = "[user78 comment's about author29 post's]", PostId = 14, PostRating = 9},
                new Comment(){ Id = 107, UserName = "user674", Content = "[user674 comment's about author29 post's]", PostId = 14, PostRating = 3},
                new Comment(){ Id = 108, UserName = "user560", Content = "[user560 comment's about author3 post's]", PostId = 15, PostRating = 9},
                new Comment(){ Id = 109, UserName = "user686", Content = "[user686 comment's about author3 post's]", PostId = 15, PostRating = 7},
                new Comment(){ Id = 110, UserName = "user589", Content = "[user589 comment's about author3 post's]", PostId = 15, PostRating = 7},
                new Comment(){ Id = 111, UserName = "user208", Content = "[user208 comment's about author3 post's]", PostId = 15, PostRating = 1},
                new Comment(){ Id = 112, UserName = "user241", Content = "[user241 comment's about author3 post's]", PostId = 15, PostRating = 4},
                new Comment(){ Id = 113, UserName = "user177", Content = "[user177 comment's about author3 post's]", PostId = 15, PostRating = 4},
                new Comment(){ Id = 114, UserName = "user333", Content = "[user333 comment's about author3 post's]", PostId = 15, PostRating = 9},
                new Comment(){ Id = 115, UserName = "user441", Content = "[user441 comment's about author3 post's]", PostId = 15, PostRating = 3},
                new Comment(){ Id = 116, UserName = "user607", Content = "[user607 comment's about author5 post's]", PostId = 16, PostRating = 9},
                new Comment(){ Id = 117, UserName = "user570", Content = "[user570 comment's about author5 post's]", PostId = 16, PostRating = 3},
                new Comment(){ Id = 118, UserName = "user464", Content = "[user464 comment's about author5 post's]", PostId = 16, PostRating = 3},
                new Comment(){ Id = 119, UserName = "user72", Content = "[user72 comment's about author5 post's]", PostId = 16, PostRating = 5},
                new Comment(){ Id = 120, UserName = "user615", Content = "[user615 comment's about author5 post's]", PostId = 16, PostRating = 4},
                new Comment(){ Id = 121, UserName = "user655", Content = "[user655 comment's about author5 post's]", PostId = 16, PostRating = 3},
                new Comment(){ Id = 122, UserName = "user459", Content = "[user459 comment's about author5 post's]", PostId = 16, PostRating = 5},
                new Comment(){ Id = 123, UserName = "user89", Content = "[user89 comment's about author5 post's]", PostId = 16, PostRating = 7},
                new Comment(){ Id = 124, UserName = "user488", Content = "[user488 comment's about author8 post's]", PostId = 17, PostRating = 5},
                new Comment(){ Id = 125, UserName = "user559", Content = "[user559 comment's about author8 post's]", PostId = 17, PostRating = 6},
                new Comment(){ Id = 126, UserName = "user578", Content = "[user578 comment's about author8 post's]", PostId = 17, PostRating = 4},
                new Comment(){ Id = 127, UserName = "user188", Content = "[user188 comment's about author8 post's]", PostId = 17, PostRating = 6},
                new Comment(){ Id = 128, UserName = "user505", Content = "[user505 comment's about author8 post's]", PostId = 17, PostRating = 1},
                new Comment(){ Id = 129, UserName = "user268", Content = "[user268 comment's about author8 post's]", PostId = 17, PostRating = 5},
                new Comment(){ Id = 130, UserName = "user572", Content = "[user572 comment's about author2 post's]", PostId = 18, PostRating = 8},
                new Comment(){ Id = 131, UserName = "user592", Content = "[user592 comment's about author2 post's]", PostId = 18, PostRating = 4},
                new Comment(){ Id = 132, UserName = "user169", Content = "[user169 comment's about author2 post's]", PostId = 18, PostRating = 3},
                new Comment(){ Id = 133, UserName = "user643", Content = "[user643 comment's about author2 post's]", PostId = 18, PostRating = 8},
                new Comment(){ Id = 134, UserName = "user433", Content = "[user433 comment's about author2 post's]", PostId = 18, PostRating = 2},
                new Comment(){ Id = 135, UserName = "user492", Content = "[user492 comment's about author2 post's]", PostId = 18, PostRating = 6},
                new Comment(){ Id = 136, UserName = "user499", Content = "[user499 comment's about author18 post's]", PostId = 19, PostRating = 1},
                new Comment(){ Id = 137, UserName = "user358", Content = "[user358 comment's about author18 post's]", PostId = 19, PostRating = 6},
                new Comment(){ Id = 138, UserName = "user481", Content = "[user481 comment's about author18 post's]", PostId = 19, PostRating = 1},
                new Comment(){ Id = 139, UserName = "user295", Content = "[user295 comment's about author18 post's]", PostId = 19, PostRating = 3},
                new Comment(){ Id = 140, UserName = "user499", Content = "[user499 comment's about author18 post's]", PostId = 19, PostRating = 9},
                new Comment(){ Id = 141, UserName = "user558", Content = "[user558 comment's about author18 post's]", PostId = 19, PostRating = 4},
                new Comment(){ Id = 142, UserName = "user516", Content = "[user516 comment's about author8 post's]", PostId = 20, PostRating = 3},
                new Comment(){ Id = 143, UserName = "user249", Content = "[user249 comment's about author8 post's]", PostId = 20, PostRating = 2},
                new Comment(){ Id = 144, UserName = "user445", Content = "[user445 comment's about author8 post's]", PostId = 20, PostRating = 9},
                new Comment(){ Id = 145, UserName = "user524", Content = "[user524 comment's about author8 post's]", PostId = 20, PostRating = 3},
                new Comment(){ Id = 146, UserName = "user175", Content = "[user175 comment's about author8 post's]", PostId = 20, PostRating = 3},
                new Comment(){ Id = 147, UserName = "user382", Content = "[user382 comment's about author28 post's]", PostId = 21, PostRating = 6},
                new Comment(){ Id = 148, UserName = "user193", Content = "[user193 comment's about author28 post's]", PostId = 21, PostRating = 3},
                new Comment(){ Id = 149, UserName = "user202", Content = "[user202 comment's about author28 post's]", PostId = 21, PostRating = 2},
                new Comment(){ Id = 150, UserName = "user498", Content = "[user498 comment's about author28 post's]", PostId = 21, PostRating = 6},
                new Comment(){ Id = 151, UserName = "user466", Content = "[user466 comment's about author28 post's]", PostId = 21, PostRating = 4},
                new Comment(){ Id = 152, UserName = "user197", Content = "[user197 comment's about author10 post's]", PostId = 22, PostRating = 8},
                new Comment(){ Id = 153, UserName = "user241", Content = "[user241 comment's about author10 post's]", PostId = 22, PostRating = 5},
                new Comment(){ Id = 154, UserName = "user71", Content = "[user71 comment's about author10 post's]", PostId = 22, PostRating = 9},
                new Comment(){ Id = 155, UserName = "user210", Content = "[user210 comment's about author10 post's]", PostId = 22, PostRating = 7},
                new Comment(){ Id = 156, UserName = "user552", Content = "[user552 comment's about author10 post's]", PostId = 22, PostRating = 4},
                new Comment(){ Id = 157, UserName = "user148", Content = "[user148 comment's about author10 post's]", PostId = 22, PostRating = 1},
                new Comment(){ Id = 158, UserName = "user451", Content = "[user451 comment's about author1 post's]", PostId = 23, PostRating = 8},
                new Comment(){ Id = 159, UserName = "user206", Content = "[user206 comment's about author1 post's]", PostId = 23, PostRating = 7},
                new Comment(){ Id = 160, UserName = "user313", Content = "[user313 comment's about author1 post's]", PostId = 23, PostRating = 2},
                new Comment(){ Id = 161, UserName = "user404", Content = "[user404 comment's about author1 post's]", PostId = 23, PostRating = 1},
                new Comment(){ Id = 162, UserName = "user430", Content = "[user430 comment's about author1 post's]", PostId = 23, PostRating = 7},
                new Comment(){ Id = 163, UserName = "user431", Content = "[user431 comment's about author10 post's]", PostId = 24, PostRating = 5},
                new Comment(){ Id = 164, UserName = "user121", Content = "[user121 comment's about author10 post's]", PostId = 24, PostRating = 3},
                new Comment(){ Id = 165, UserName = "user393", Content = "[user393 comment's about author10 post's]", PostId = 24, PostRating = 8},
                new Comment(){ Id = 166, UserName = "user71", Content = "[user71 comment's about author10 post's]", PostId = 24, PostRating = 1},
                new Comment(){ Id = 167, UserName = "user528", Content = "[user528 comment's about author10 post's]", PostId = 24, PostRating = 5},
                new Comment(){ Id = 168, UserName = "user211", Content = "[user211 comment's about author10 post's]", PostId = 24, PostRating = 6},
                new Comment(){ Id = 169, UserName = "user449", Content = "[user449 comment's about author9 post's]", PostId = 25, PostRating = 3},
                new Comment(){ Id = 170, UserName = "user309", Content = "[user309 comment's about author9 post's]", PostId = 25, PostRating = 8},
                new Comment(){ Id = 171, UserName = "user103", Content = "[user103 comment's about author9 post's]", PostId = 25, PostRating = 1},
                new Comment(){ Id = 172, UserName = "user220", Content = "[user220 comment's about author9 post's]", PostId = 25, PostRating = 3},
                new Comment(){ Id = 173, UserName = "user189", Content = "[user189 comment's about author9 post's]", PostId = 25, PostRating = 4},
                new Comment(){ Id = 174, UserName = "user488", Content = "[user488 comment's about author9 post's]", PostId = 25, PostRating = 1},
                new Comment(){ Id = 175, UserName = "user201", Content = "[user201 comment's about author9 post's]", PostId = 25, PostRating = 8},
                new Comment(){ Id = 176, UserName = "user405", Content = "[user405 comment's about author4 post's]", PostId = 26, PostRating = 3},
                new Comment(){ Id = 177, UserName = "user332", Content = "[user332 comment's about author4 post's]", PostId = 26, PostRating = 4},
                new Comment(){ Id = 178, UserName = "user682", Content = "[user682 comment's about author4 post's]", PostId = 26, PostRating = 8},
                new Comment(){ Id = 179, UserName = "user606", Content = "[user606 comment's about author4 post's]", PostId = 26, PostRating = 6},
                new Comment(){ Id = 180, UserName = "user624", Content = "[user624 comment's about author4 post's]", PostId = 26, PostRating = 1},
                new Comment(){ Id = 181, UserName = "user507", Content = "[user507 comment's about author4 post's]", PostId = 26, PostRating = 2},
                new Comment(){ Id = 182, UserName = "user592", Content = "[user592 comment's about author4 post's]", PostId = 26, PostRating = 2},
                new Comment(){ Id = 183, UserName = "user200", Content = "[user200 comment's about author4 post's]", PostId = 26, PostRating = 8},
                new Comment(){ Id = 184, UserName = "user681", Content = "[user681 comment's about author4 post's]", PostId = 26, PostRating = 9},
                new Comment(){ Id = 185, UserName = "user380", Content = "[user380 comment's about author4 post's]", PostId = 26, PostRating = 6},
                new Comment(){ Id = 186, UserName = "user201", Content = "[user201 comment's about author15 post's]", PostId = 27, PostRating = 6},
                new Comment(){ Id = 187, UserName = "user463", Content = "[user463 comment's about author15 post's]", PostId = 27, PostRating = 3},
                new Comment(){ Id = 188, UserName = "user267", Content = "[user267 comment's about author15 post's]", PostId = 27, PostRating = 1},
                new Comment(){ Id = 189, UserName = "user428", Content = "[user428 comment's about author15 post's]", PostId = 27, PostRating = 1},
                new Comment(){ Id = 190, UserName = "user131", Content = "[user131 comment's about author15 post's]", PostId = 27, PostRating = 4},
                new Comment(){ Id = 191, UserName = "user130", Content = "[user130 comment's about author15 post's]", PostId = 27, PostRating = 1},
                new Comment(){ Id = 192, UserName = "user55", Content = "[user55 comment's about author15 post's]", PostId = 27, PostRating = 8},
                new Comment(){ Id = 193, UserName = "user254", Content = "[user254 comment's about author15 post's]", PostId = 27, PostRating = 4},
                new Comment(){ Id = 194, UserName = "user351", Content = "[user351 comment's about author15 post's]", PostId = 27, PostRating = 4},
                new Comment(){ Id = 195, UserName = "user352", Content = "[user352 comment's about author15 post's]", PostId = 27, PostRating = 3},
                new Comment(){ Id = 196, UserName = "user282", Content = "[user282 comment's about author15 post's]", PostId = 27, PostRating = 2},
                new Comment(){ Id = 197, UserName = "user543", Content = "[user543 comment's about author15 post's]", PostId = 27, PostRating = 8},
                new Comment(){ Id = 198, UserName = "user605", Content = "[user605 comment's about author5 post's]", PostId = 28, PostRating = 7},
                new Comment(){ Id = 199, UserName = "user243", Content = "[user243 comment's about author5 post's]", PostId = 28, PostRating = 5},
                new Comment(){ Id = 200, UserName = "user615", Content = "[user615 comment's about author5 post's]", PostId = 28, PostRating = 5},
                new Comment(){ Id = 201, UserName = "user353", Content = "[user353 comment's about author5 post's]", PostId = 28, PostRating = 3},
                new Comment(){ Id = 202, UserName = "user348", Content = "[user348 comment's about author5 post's]", PostId = 28, PostRating = 3},
                new Comment(){ Id = 203, UserName = "user646", Content = "[user646 comment's about author5 post's]", PostId = 28, PostRating = 2},
                new Comment(){ Id = 204, UserName = "user161", Content = "[user161 comment's about author5 post's]", PostId = 28, PostRating = 9},
                new Comment(){ Id = 205, UserName = "user615", Content = "[user615 comment's about author5 post's]", PostId = 28, PostRating = 8},
                new Comment(){ Id = 206, UserName = "user195", Content = "[user195 comment's about author5 post's]", PostId = 28, PostRating = 9},
                new Comment(){ Id = 207, UserName = "user288", Content = "[user288 comment's about author5 post's]", PostId = 28, PostRating = 6},
                new Comment(){ Id = 208, UserName = "user685", Content = "[user685 comment's about author5 post's]", PostId = 28, PostRating = 5},
                new Comment(){ Id = 209, UserName = "user558", Content = "[user558 comment's about author5 post's]", PostId = 28, PostRating = 1},
                new Comment(){ Id = 210, UserName = "user194", Content = "[user194 comment's about author5 post's]", PostId = 28, PostRating = 1},
                new Comment(){ Id = 211, UserName = "user563", Content = "[user563 comment's about author7 post's]", PostId = 29, PostRating = 5},
                new Comment(){ Id = 212, UserName = "user504", Content = "[user504 comment's about author7 post's]", PostId = 29, PostRating = 5},
                new Comment(){ Id = 213, UserName = "user628", Content = "[user628 comment's about author7 post's]", PostId = 29, PostRating = 8},
                new Comment(){ Id = 214, UserName = "user269", Content = "[user269 comment's about author7 post's]", PostId = 29, PostRating = 1},
                new Comment(){ Id = 215, UserName = "user689", Content = "[user689 comment's about author7 post's]", PostId = 29, PostRating = 8},
                new Comment(){ Id = 216, UserName = "user97", Content = "[user97 comment's about author7 post's]", PostId = 29, PostRating = 6},
                new Comment(){ Id = 217, UserName = "user376", Content = "[user376 comment's about author7 post's]", PostId = 29, PostRating = 9},
                new Comment(){ Id = 218, UserName = "user368", Content = "[user368 comment's about author7 post's]", PostId = 29, PostRating = 7},
                new Comment(){ Id = 219, UserName = "user121", Content = "[user121 comment's about author20 post's]", PostId = 30, PostRating = 2},
                new Comment(){ Id = 220, UserName = "user378", Content = "[user378 comment's about author20 post's]", PostId = 30, PostRating = 6},
                new Comment(){ Id = 221, UserName = "user83", Content = "[user83 comment's about author20 post's]", PostId = 30, PostRating = 9},
                new Comment(){ Id = 222, UserName = "user178", Content = "[user178 comment's about author20 post's]", PostId = 30, PostRating = 4},
                new Comment(){ Id = 223, UserName = "user494", Content = "[user494 comment's about author20 post's]", PostId = 30, PostRating = 6},
                new Comment(){ Id = 224, UserName = "user179", Content = "[user179 comment's about author20 post's]", PostId = 30, PostRating = 6},
                new Comment(){ Id = 225, UserName = "user62", Content = "[user62 comment's about author20 post's]", PostId = 30, PostRating = 9},
                new Comment(){ Id = 226, UserName = "user60", Content = "[user60 comment's about author20 post's]", PostId = 30, PostRating = 8},
                new Comment(){ Id = 227, UserName = "user682", Content = "[user682 comment's about author20 post's]", PostId = 30, PostRating = 4},
                new Comment(){ Id = 228, UserName = "user238", Content = "[user238 comment's about author9 post's]", PostId = 31, PostRating = 3},
                new Comment(){ Id = 229, UserName = "user555", Content = "[user555 comment's about author9 post's]", PostId = 31, PostRating = 4},
                new Comment(){ Id = 230, UserName = "user408", Content = "[user408 comment's about author9 post's]", PostId = 31, PostRating = 8},
                new Comment(){ Id = 231, UserName = "user565", Content = "[user565 comment's about author9 post's]", PostId = 31, PostRating = 8},
                new Comment(){ Id = 232, UserName = "user318", Content = "[user318 comment's about author9 post's]", PostId = 31, PostRating = 9},
                new Comment(){ Id = 233, UserName = "user207", Content = "[user207 comment's about author9 post's]", PostId = 31, PostRating = 9},
                new Comment(){ Id = 234, UserName = "user626", Content = "[user626 comment's about author16 post's]", PostId = 32, PostRating = 2},
                new Comment(){ Id = 235, UserName = "user248", Content = "[user248 comment's about author16 post's]", PostId = 32, PostRating = 1},
                new Comment(){ Id = 236, UserName = "user194", Content = "[user194 comment's about author16 post's]", PostId = 32, PostRating = 3},
                new Comment(){ Id = 237, UserName = "user159", Content = "[user159 comment's about author16 post's]", PostId = 32, PostRating = 1},
                new Comment(){ Id = 238, UserName = "user100", Content = "[user100 comment's about author16 post's]", PostId = 32, PostRating = 9},
                new Comment(){ Id = 239, UserName = "user574", Content = "[user574 comment's about author16 post's]", PostId = 32, PostRating = 1},
                new Comment(){ Id = 240, UserName = "user115", Content = "[user115 comment's about author16 post's]", PostId = 32, PostRating = 6},
                new Comment(){ Id = 241, UserName = "user153", Content = "[user153 comment's about author16 post's]", PostId = 32, PostRating = 7},
                new Comment(){ Id = 242, UserName = "user328", Content = "[user328 comment's about author16 post's]", PostId = 32, PostRating = 9},
                new Comment(){ Id = 243, UserName = "user116", Content = "[user116 comment's about author16 post's]", PostId = 32, PostRating = 2},
                new Comment(){ Id = 244, UserName = "user305", Content = "[user305 comment's about author6 post's]", PostId = 33, PostRating = 1},
                new Comment(){ Id = 245, UserName = "user113", Content = "[user113 comment's about author6 post's]", PostId = 33, PostRating = 4},
                new Comment(){ Id = 246, UserName = "user440", Content = "[user440 comment's about author6 post's]", PostId = 33, PostRating = 3},
                new Comment(){ Id = 247, UserName = "user238", Content = "[user238 comment's about author19 post's]", PostId = 34, PostRating = 7},
                new Comment(){ Id = 248, UserName = "user74", Content = "[user74 comment's about author19 post's]", PostId = 34, PostRating = 7},
                new Comment(){ Id = 249, UserName = "user511", Content = "[user511 comment's about author19 post's]", PostId = 34, PostRating = 8},
                new Comment(){ Id = 250, UserName = "user353", Content = "[user353 comment's about author19 post's]", PostId = 34, PostRating = 5},
                new Comment(){ Id = 251, UserName = "user101", Content = "[user101 comment's about author19 post's]", PostId = 34, PostRating = 8},
                new Comment(){ Id = 252, UserName = "user332", Content = "[user332 comment's about author6 post's]", PostId = 35, PostRating = 1},
                new Comment(){ Id = 253, UserName = "user358", Content = "[user358 comment's about author6 post's]", PostId = 35, PostRating = 2},
                new Comment(){ Id = 254, UserName = "user345", Content = "[user345 comment's about author6 post's]", PostId = 35, PostRating = 1},
                new Comment(){ Id = 255, UserName = "user99", Content = "[user99 comment's about author6 post's]", PostId = 35, PostRating = 2},
                new Comment(){ Id = 256, UserName = "user276", Content = "[user276 comment's about author5 post's]", PostId = 36, PostRating = 1},
                new Comment(){ Id = 257, UserName = "user354", Content = "[user354 comment's about author5 post's]", PostId = 36, PostRating = 9},
                new Comment(){ Id = 258, UserName = "user178", Content = "[user178 comment's about author5 post's]", PostId = 36, PostRating = 6},
                new Comment(){ Id = 259, UserName = "user145", Content = "[user145 comment's about author5 post's]", PostId = 36, PostRating = 2},
                new Comment(){ Id = 260, UserName = "user184", Content = "[user184 comment's about author5 post's]", PostId = 36, PostRating = 5},
                new Comment(){ Id = 261, UserName = "user599", Content = "[user599 comment's about author16 post's]", PostId = 37, PostRating = 7},
                new Comment(){ Id = 262, UserName = "user677", Content = "[user677 comment's about author16 post's]", PostId = 37, PostRating = 1},
                new Comment(){ Id = 263, UserName = "user182", Content = "[user182 comment's about author16 post's]", PostId = 37, PostRating = 7},
                new Comment(){ Id = 264, UserName = "user446", Content = "[user446 comment's about author16 post's]", PostId = 37, PostRating = 4},
                new Comment(){ Id = 265, UserName = "user496", Content = "[user496 comment's about author16 post's]", PostId = 37, PostRating = 9},
                new Comment(){ Id = 266, UserName = "user551", Content = "[user551 comment's about author16 post's]", PostId = 37, PostRating = 2},
                new Comment(){ Id = 267, UserName = "user375", Content = "[user375 comment's about author16 post's]", PostId = 37, PostRating = 9},
                new Comment(){ Id = 268, UserName = "user590", Content = "[user590 comment's about author16 post's]", PostId = 37, PostRating = 9},
                new Comment(){ Id = 269, UserName = "user683", Content = "[user683 comment's about author16 post's]", PostId = 37, PostRating = 7},
                new Comment(){ Id = 270, UserName = "user321", Content = "[user321 comment's about author26 post's]", PostId = 38, PostRating = 6},
                new Comment(){ Id = 271, UserName = "user205", Content = "[user205 comment's about author26 post's]", PostId = 38, PostRating = 7},
                new Comment(){ Id = 272, UserName = "user108", Content = "[user108 comment's about author26 post's]", PostId = 38, PostRating = 1},
                new Comment(){ Id = 273, UserName = "user501", Content = "[user501 comment's about author26 post's]", PostId = 38, PostRating = 3},
                new Comment(){ Id = 274, UserName = "user85", Content = "[user85 comment's about author26 post's]", PostId = 38, PostRating = 2},
                new Comment(){ Id = 275, UserName = "user397", Content = "[user397 comment's about author26 post's]", PostId = 38, PostRating = 3},
                new Comment(){ Id = 276, UserName = "user509", Content = "[user509 comment's about author26 post's]", PostId = 38, PostRating = 1},
                new Comment(){ Id = 277, UserName = "user574", Content = "[user574 comment's about author5 post's]", PostId = 39, PostRating = 4},
                new Comment(){ Id = 278, UserName = "user313", Content = "[user313 comment's about author5 post's]", PostId = 39, PostRating = 1},
                new Comment(){ Id = 279, UserName = "user210", Content = "[user210 comment's about author5 post's]", PostId = 39, PostRating = 8},
                new Comment(){ Id = 280, UserName = "user487", Content = "[user487 comment's about author29 post's]", PostId = 40, PostRating = 7},
                new Comment(){ Id = 281, UserName = "user193", Content = "[user193 comment's about author29 post's]", PostId = 40, PostRating = 3},
                new Comment(){ Id = 282, UserName = "user122", Content = "[user122 comment's about author29 post's]", PostId = 40, PostRating = 4},
                new Comment(){ Id = 283, UserName = "user549", Content = "[user549 comment's about author29 post's]", PostId = 40, PostRating = 2},
                new Comment(){ Id = 284, UserName = "user635", Content = "[user635 comment's about author29 post's]", PostId = 40, PostRating = 1},
                new Comment(){ Id = 285, UserName = "user647", Content = "[user647 comment's about author29 post's]", PostId = 40, PostRating = 4},
                new Comment(){ Id = 286, UserName = "user63", Content = "[user63 comment's about author29 post's]", PostId = 40, PostRating = 9},
                new Comment(){ Id = 287, UserName = "user112", Content = "[user112 comment's about author27 post's]", PostId = 41, PostRating = 4},
                new Comment(){ Id = 288, UserName = "user430", Content = "[user430 comment's about author27 post's]", PostId = 41, PostRating = 1},
                new Comment(){ Id = 289, UserName = "user683", Content = "[user683 comment's about author27 post's]", PostId = 41, PostRating = 3},
                new Comment(){ Id = 290, UserName = "user145", Content = "[user145 comment's about author27 post's]", PostId = 41, PostRating = 1},
                new Comment(){ Id = 291, UserName = "user698", Content = "[user698 comment's about author27 post's]", PostId = 41, PostRating = 8},
                new Comment(){ Id = 292, UserName = "user237", Content = "[user237 comment's about author27 post's]", PostId = 41, PostRating = 6},
                new Comment(){ Id = 293, UserName = "user427", Content = "[user427 comment's about author27 post's]", PostId = 41, PostRating = 7},
                new Comment(){ Id = 294, UserName = "user473", Content = "[user473 comment's about author6 post's]", PostId = 42, PostRating = 7},
                new Comment(){ Id = 295, UserName = "user252", Content = "[user252 comment's about author6 post's]", PostId = 42, PostRating = 5},
                new Comment(){ Id = 296, UserName = "user688", Content = "[user688 comment's about author6 post's]", PostId = 42, PostRating = 9},
                new Comment(){ Id = 297, UserName = "user188", Content = "[user188 comment's about author6 post's]", PostId = 42, PostRating = 9},
                new Comment(){ Id = 298, UserName = "user659", Content = "[user659 comment's about author24 post's]", PostId = 43, PostRating = 4},
                new Comment(){ Id = 299, UserName = "user556", Content = "[user556 comment's about author24 post's]", PostId = 43, PostRating = 9},
                new Comment(){ Id = 300, UserName = "user311", Content = "[user311 comment's about author24 post's]", PostId = 43, PostRating = 7},
                new Comment(){ Id = 301, UserName = "user452", Content = "[user452 comment's about author24 post's]", PostId = 43, PostRating = 9},
                new Comment(){ Id = 302, UserName = "user261", Content = "[user261 comment's about author24 post's]", PostId = 43, PostRating = 5},
                new Comment(){ Id = 303, UserName = "user105", Content = "[user105 comment's about author24 post's]", PostId = 43, PostRating = 6},
                new Comment(){ Id = 304, UserName = "user297", Content = "[user297 comment's about author24 post's]", PostId = 43, PostRating = 5},
                new Comment(){ Id = 305, UserName = "user89", Content = "[user89 comment's about author27 post's]", PostId = 44, PostRating = 5},
                new Comment(){ Id = 306, UserName = "user311", Content = "[user311 comment's about author27 post's]", PostId = 44, PostRating = 3},
                new Comment(){ Id = 307, UserName = "user135", Content = "[user135 comment's about author27 post's]", PostId = 44, PostRating = 1},
                new Comment(){ Id = 308, UserName = "user242", Content = "[user242 comment's about author27 post's]", PostId = 44, PostRating = 8},
                new Comment(){ Id = 309, UserName = "user493", Content = "[user493 comment's about author27 post's]", PostId = 44, PostRating = 9},
                new Comment(){ Id = 310, UserName = "user251", Content = "[user251 comment's about author27 post's]", PostId = 44, PostRating = 1},
                new Comment(){ Id = 311, UserName = "user642", Content = "[user642 comment's about author27 post's]", PostId = 44, PostRating = 8},
                new Comment(){ Id = 312, UserName = "user442", Content = "[user442 comment's about author27 post's]", PostId = 44, PostRating = 1},
                new Comment(){ Id = 313, UserName = "user114", Content = "[user114 comment's about author24 post's]", PostId = 45, PostRating = 1},
                new Comment(){ Id = 314, UserName = "user299", Content = "[user299 comment's about author24 post's]", PostId = 45, PostRating = 5},
                new Comment(){ Id = 315, UserName = "user614", Content = "[user614 comment's about author24 post's]", PostId = 45, PostRating = 9},
                new Comment(){ Id = 316, UserName = "user251", Content = "[user251 comment's about author24 post's]", PostId = 45, PostRating = 5},
                new Comment(){ Id = 317, UserName = "user582", Content = "[user582 comment's about author24 post's]", PostId = 45, PostRating = 2},
                new Comment(){ Id = 318, UserName = "user152", Content = "[user152 comment's about author24 post's]", PostId = 45, PostRating = 1},
                new Comment(){ Id = 319, UserName = "user635", Content = "[user635 comment's about author24 post's]", PostId = 45, PostRating = 7},
                new Comment(){ Id = 320, UserName = "user414", Content = "[user414 comment's about author5 post's]", PostId = 46, PostRating = 2},
                new Comment(){ Id = 321, UserName = "user298", Content = "[user298 comment's about author5 post's]", PostId = 46, PostRating = 3},
                new Comment(){ Id = 322, UserName = "user531", Content = "[user531 comment's about author5 post's]", PostId = 46, PostRating = 6},
                new Comment(){ Id = 323, UserName = "user638", Content = "[user638 comment's about author5 post's]", PostId = 46, PostRating = 5},
                new Comment(){ Id = 324, UserName = "user331", Content = "[user331 comment's about author5 post's]", PostId = 46, PostRating = 8},
                new Comment(){ Id = 325, UserName = "user127", Content = "[user127 comment's about author5 post's]", PostId = 46, PostRating = 4},
                new Comment(){ Id = 326, UserName = "user532", Content = "[user532 comment's about author5 post's]", PostId = 46, PostRating = 2},
                new Comment(){ Id = 327, UserName = "user197", Content = "[user197 comment's about author29 post's]", PostId = 47, PostRating = 1},
                new Comment(){ Id = 328, UserName = "user359", Content = "[user359 comment's about author29 post's]", PostId = 47, PostRating = 4},
                new Comment(){ Id = 329, UserName = "user617", Content = "[user617 comment's about author29 post's]", PostId = 47, PostRating = 7},
                new Comment(){ Id = 330, UserName = "user677", Content = "[user677 comment's about author29 post's]", PostId = 47, PostRating = 6},
                new Comment(){ Id = 331, UserName = "user393", Content = "[user393 comment's about author29 post's]", PostId = 47, PostRating = 4},
                new Comment(){ Id = 332, UserName = "user527", Content = "[user527 comment's about author29 post's]", PostId = 47, PostRating = 2},
                new Comment(){ Id = 333, UserName = "user612", Content = "[user612 comment's about author7 post's]", PostId = 48, PostRating = 9},
                new Comment(){ Id = 334, UserName = "user527", Content = "[user527 comment's about author7 post's]", PostId = 48, PostRating = 6},
                new Comment(){ Id = 335, UserName = "user162", Content = "[user162 comment's about author7 post's]", PostId = 48, PostRating = 1},
                new Comment(){ Id = 336, UserName = "user357", Content = "[user357 comment's about author7 post's]", PostId = 48, PostRating = 6},
                new Comment(){ Id = 337, UserName = "user115", Content = "[user115 comment's about author7 post's]", PostId = 48, PostRating = 5},
                new Comment(){ Id = 338, UserName = "user424", Content = "[user424 comment's about author5 post's]", PostId = 49, PostRating = 2},
                new Comment(){ Id = 339, UserName = "user278", Content = "[user278 comment's about author5 post's]", PostId = 49, PostRating = 7},
                new Comment(){ Id = 340, UserName = "user121", Content = "[user121 comment's about author5 post's]", PostId = 49, PostRating = 1},
                new Comment(){ Id = 341, UserName = "user609", Content = "[user609 comment's about author5 post's]", PostId = 49, PostRating = 8},
                new Comment(){ Id = 342, UserName = "user390", Content = "[user390 comment's about author5 post's]", PostId = 49, PostRating = 1},
                new Comment(){ Id = 343, UserName = "user208", Content = "[user208 comment's about author5 post's]", PostId = 49, PostRating = 6},
                new Comment(){ Id = 344, UserName = "user442", Content = "[user442 comment's about author5 post's]", PostId = 49, PostRating = 3},
                new Comment(){ Id = 345, UserName = "user395", Content = "[user395 comment's about author5 post's]", PostId = 49, PostRating = 3},
                new Comment(){ Id = 346, UserName = "user115", Content = "[user115 comment's about author5 post's]", PostId = 49, PostRating = 7},
                new Comment(){ Id = 347, UserName = "user555", Content = "[user555 comment's about author10 post's]", PostId = 50, PostRating = 3},
                new Comment(){ Id = 348, UserName = "user245", Content = "[user245 comment's about author10 post's]", PostId = 50, PostRating = 5},
                new Comment(){ Id = 349, UserName = "user454", Content = "[user454 comment's about author10 post's]", PostId = 50, PostRating = 8},
                new Comment(){ Id = 350, UserName = "user382", Content = "[user382 comment's about author10 post's]", PostId = 50, PostRating = 4},
                new Comment(){ Id = 351, UserName = "user146", Content = "[user146 comment's about author10 post's]", PostId = 50, PostRating = 7},
                new Comment(){ Id = 352, UserName = "user128", Content = "[user128 comment's about author10 post's]", PostId = 50, PostRating = 4},
                new Comment(){ Id = 353, UserName = "user198", Content = "[user198 comment's about author10 post's]", PostId = 50, PostRating = 5},
                new Comment(){ Id = 354, UserName = "user595", Content = "[user595 comment's about author22 post's]", PostId = 51, PostRating = 5},
                new Comment(){ Id = 355, UserName = "user662", Content = "[user662 comment's about author22 post's]", PostId = 51, PostRating = 7},
                new Comment(){ Id = 356, UserName = "user540", Content = "[user540 comment's about author22 post's]", PostId = 51, PostRating = 8},
                new Comment(){ Id = 357, UserName = "user110", Content = "[user110 comment's about author22 post's]", PostId = 51, PostRating = 2},
                new Comment(){ Id = 358, UserName = "user535", Content = "[user535 comment's about author22 post's]", PostId = 51, PostRating = 1},
                new Comment(){ Id = 359, UserName = "user689", Content = "[user689 comment's about author22 post's]", PostId = 51, PostRating = 1},
                new Comment(){ Id = 360, UserName = "user570", Content = "[user570 comment's about author22 post's]", PostId = 51, PostRating = 1},
                new Comment(){ Id = 361, UserName = "user143", Content = "[user143 comment's about author22 post's]", PostId = 51, PostRating = 7},
                new Comment(){ Id = 362, UserName = "user63", Content = "[user63 comment's about author19 post's]", PostId = 52, PostRating = 8},
                new Comment(){ Id = 363, UserName = "user438", Content = "[user438 comment's about author19 post's]", PostId = 52, PostRating = 5},
                new Comment(){ Id = 364, UserName = "user492", Content = "[user492 comment's about author19 post's]", PostId = 52, PostRating = 5},
                new Comment(){ Id = 365, UserName = "user642", Content = "[user642 comment's about author19 post's]", PostId = 52, PostRating = 2},
                new Comment(){ Id = 366, UserName = "user471", Content = "[user471 comment's about author19 post's]", PostId = 52, PostRating = 9},
                new Comment(){ Id = 367, UserName = "user438", Content = "[user438 comment's about author19 post's]", PostId = 52, PostRating = 8},
                new Comment(){ Id = 368, UserName = "user481", Content = "[user481 comment's about author19 post's]", PostId = 52, PostRating = 5},
                new Comment(){ Id = 369, UserName = "user421", Content = "[user421 comment's about author19 post's]", PostId = 52, PostRating = 2},
                new Comment(){ Id = 370, UserName = "user547", Content = "[user547 comment's about author25 post's]", PostId = 53, PostRating = 2},
                new Comment(){ Id = 371, UserName = "user121", Content = "[user121 comment's about author25 post's]", PostId = 53, PostRating = 9},
                new Comment(){ Id = 372, UserName = "user574", Content = "[user574 comment's about author25 post's]", PostId = 53, PostRating = 9},
                new Comment(){ Id = 373, UserName = "user453", Content = "[user453 comment's about author25 post's]", PostId = 53, PostRating = 4},
                new Comment(){ Id = 374, UserName = "user291", Content = "[user291 comment's about author25 post's]", PostId = 53, PostRating = 7},
                new Comment(){ Id = 375, UserName = "user148", Content = "[user148 comment's about author25 post's]", PostId = 53, PostRating = 6},
                new Comment(){ Id = 376, UserName = "user261", Content = "[user261 comment's about author12 post's]", PostId = 54, PostRating = 4},
                new Comment(){ Id = 377, UserName = "user270", Content = "[user270 comment's about author12 post's]", PostId = 54, PostRating = 1},
                new Comment(){ Id = 378, UserName = "user477", Content = "[user477 comment's about author12 post's]", PostId = 54, PostRating = 9},
                new Comment(){ Id = 379, UserName = "user289", Content = "[user289 comment's about author12 post's]", PostId = 54, PostRating = 9},
                new Comment(){ Id = 380, UserName = "user532", Content = "[user532 comment's about author12 post's]", PostId = 54, PostRating = 3},
                new Comment(){ Id = 381, UserName = "user61", Content = "[user61 comment's about author12 post's]", PostId = 54, PostRating = 7},
                new Comment(){ Id = 382, UserName = "user140", Content = "[user140 comment's about author12 post's]", PostId = 54, PostRating = 4},
                new Comment(){ Id = 383, UserName = "user152", Content = "[user152 comment's about author12 post's]", PostId = 54, PostRating = 8},
                new Comment(){ Id = 384, UserName = "user347", Content = "[user347 comment's about author3 post's]", PostId = 55, PostRating = 8},
                new Comment(){ Id = 385, UserName = "user355", Content = "[user355 comment's about author3 post's]", PostId = 55, PostRating = 9},
                new Comment(){ Id = 386, UserName = "user583", Content = "[user583 comment's about author3 post's]", PostId = 55, PostRating = 9},
                new Comment(){ Id = 387, UserName = "user453", Content = "[user453 comment's about author3 post's]", PostId = 55, PostRating = 6},
                new Comment(){ Id = 388, UserName = "user252", Content = "[user252 comment's about author3 post's]", PostId = 55, PostRating = 1},
                new Comment(){ Id = 389, UserName = "user56", Content = "[user56 comment's about author3 post's]", PostId = 55, PostRating = 5},
                new Comment(){ Id = 390, UserName = "user55", Content = "[user55 comment's about author3 post's]", PostId = 55, PostRating = 4},
                new Comment(){ Id = 391, UserName = "user416", Content = "[user416 comment's about author3 post's]", PostId = 55, PostRating = 3},
                new Comment(){ Id = 392, UserName = "user489", Content = "[user489 comment's about author3 post's]", PostId = 55, PostRating = 4},
                new Comment(){ Id = 393, UserName = "user159", Content = "[user159 comment's about author3 post's]", PostId = 55, PostRating = 5},
                new Comment(){ Id = 394, UserName = "user206", Content = "[user206 comment's about author3 post's]", PostId = 55, PostRating = 8},
                new Comment(){ Id = 395, UserName = "user376", Content = "[user376 comment's about author19 post's]", PostId = 56, PostRating = 1},
                new Comment(){ Id = 396, UserName = "user313", Content = "[user313 comment's about author19 post's]", PostId = 56, PostRating = 7},
                new Comment(){ Id = 397, UserName = "user151", Content = "[user151 comment's about author19 post's]", PostId = 56, PostRating = 3},
                new Comment(){ Id = 398, UserName = "user94", Content = "[user94 comment's about author19 post's]", PostId = 56, PostRating = 5},
                new Comment(){ Id = 399, UserName = "user614", Content = "[user614 comment's about author19 post's]", PostId = 56, PostRating = 6},
                new Comment(){ Id = 400, UserName = "user185", Content = "[user185 comment's about author19 post's]", PostId = 56, PostRating = 6},
                new Comment(){ Id = 401, UserName = "user631", Content = "[user631 comment's about author19 post's]", PostId = 56, PostRating = 5},
                new Comment(){ Id = 402, UserName = "user306", Content = "[user306 comment's about author24 post's]", PostId = 57, PostRating = 3},
                new Comment(){ Id = 403, UserName = "user581", Content = "[user581 comment's about author24 post's]", PostId = 57, PostRating = 8},
                new Comment(){ Id = 404, UserName = "user398", Content = "[user398 comment's about author24 post's]", PostId = 57, PostRating = 9},
                new Comment(){ Id = 405, UserName = "user61", Content = "[user61 comment's about author24 post's]", PostId = 57, PostRating = 3},
                new Comment(){ Id = 406, UserName = "user687", Content = "[user687 comment's about author24 post's]", PostId = 57, PostRating = 8},
                new Comment(){ Id = 407, UserName = "user133", Content = "[user133 comment's about author24 post's]", PostId = 57, PostRating = 2},
                new Comment(){ Id = 408, UserName = "user272", Content = "[user272 comment's about author24 post's]", PostId = 57, PostRating = 2},
                new Comment(){ Id = 409, UserName = "user468", Content = "[user468 comment's about author24 post's]", PostId = 57, PostRating = 2},
                new Comment(){ Id = 410, UserName = "user463", Content = "[user463 comment's about author24 post's]", PostId = 57, PostRating = 9},
                new Comment(){ Id = 411, UserName = "user434", Content = "[user434 comment's about author19 post's]", PostId = 58, PostRating = 1},
                new Comment(){ Id = 412, UserName = "user253", Content = "[user253 comment's about author19 post's]", PostId = 58, PostRating = 6},
                new Comment(){ Id = 413, UserName = "user339", Content = "[user339 comment's about author19 post's]", PostId = 58, PostRating = 9},
                new Comment(){ Id = 414, UserName = "user653", Content = "[user653 comment's about author19 post's]", PostId = 58, PostRating = 4},
                new Comment(){ Id = 415, UserName = "user462", Content = "[user462 comment's about author19 post's]", PostId = 58, PostRating = 4},
                new Comment(){ Id = 416, UserName = "user435", Content = "[user435 comment's about author19 post's]", PostId = 58, PostRating = 6},
                new Comment(){ Id = 417, UserName = "user671", Content = "[user671 comment's about author12 post's]", PostId = 59, PostRating = 7},
                new Comment(){ Id = 418, UserName = "user132", Content = "[user132 comment's about author12 post's]", PostId = 59, PostRating = 8},
                new Comment(){ Id = 419, UserName = "user668", Content = "[user668 comment's about author12 post's]", PostId = 59, PostRating = 5},
                new Comment(){ Id = 420, UserName = "user382", Content = "[user382 comment's about author12 post's]", PostId = 59, PostRating = 9},
                new Comment(){ Id = 421, UserName = "user512", Content = "[user512 comment's about author12 post's]", PostId = 59, PostRating = 9},
                new Comment(){ Id = 422, UserName = "user385", Content = "[user385 comment's about author12 post's]", PostId = 59, PostRating = 1},
                new Comment(){ Id = 423, UserName = "user551", Content = "[user551 comment's about author12 post's]", PostId = 59, PostRating = 9},
                new Comment(){ Id = 424, UserName = "user171", Content = "[user171 comment's about author12 post's]", PostId = 59, PostRating = 6},
                new Comment(){ Id = 425, UserName = "user376", Content = "[user376 comment's about author16 post's]", PostId = 60, PostRating = 4},
                new Comment(){ Id = 426, UserName = "user316", Content = "[user316 comment's about author16 post's]", PostId = 60, PostRating = 8},
                new Comment(){ Id = 427, UserName = "user91", Content = "[user91 comment's about author16 post's]", PostId = 60, PostRating = 9},
                new Comment(){ Id = 428, UserName = "user363", Content = "[user363 comment's about author16 post's]", PostId = 60, PostRating = 9},
                new Comment(){ Id = 429, UserName = "user676", Content = "[user676 comment's about author16 post's]", PostId = 60, PostRating = 8}
            };


            modelBuilder.Entity<Blog>().HasData(blogs);
            modelBuilder.Entity<Post>().HasData(posts);
            modelBuilder.Entity<Comment>().HasData(comments);
        }
    }
}
