using BlogApp.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace BlogApp.Repository.Database
{
    public class BlogDbContext : DbContext
    {
        public BlogDbContext()
        {
            Database.EnsureCreated();
        }

        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder
                    .UseLazyLoadingProxies()
                    .UseInMemoryDatabase("blogs");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Post>(post => post
                .HasOne(post => post.Blog)
                .WithMany(blog => blog.Posts)
                .HasForeignKey(post => post.BlogId)
                .OnDelete(DeleteBehavior.Cascade));

            modelBuilder.Entity<Comment>(comment => comment
                .HasOne(comment => comment.Post)
                .WithMany(post => post.Comments)
                .HasForeignKey(comment => comment.PostId)
                .OnDelete(DeleteBehavior.Cascade)
            );

            List<Blog> blogs = new List<Blog>()
            {
                new Blog() { Id = 1, BlogName = "blog1"},
                new Blog() { Id = 2, BlogName = "blog2"},
                new Blog() { Id = 3, BlogName = "blog3"},
                new Blog() { Id = 4, BlogName = "blog4"},
                new Blog() { Id = 5, BlogName = "blog5"},
                new Blog() { Id = 6, BlogName = "blog6"},
                new Blog() { Id = 7, BlogName = "blog7"},
                new Blog() { Id = 8, BlogName = "blog8"},
                new Blog() { Id = 9, BlogName = "blog9"},
                new Blog() { Id = 10, BlogName = "blog10"}
            };

            List<Post> posts = new List<Post>()
            {
                new Post(){ Id = 1, PostTitle = "[author1 post's title]", PostAuthor = "author1", PostBody = "[author1 post's body]", BlogId = 9, Category = "Finance"},
                new Post(){ Id = 2, PostTitle = "[author9 post's title]", PostAuthor = "author9", PostBody = "[author9 post's body]", BlogId = 9, Category = "Finance"},
                new Post(){ Id = 3, PostTitle = "[author23 post's title]", PostAuthor = "author23", PostBody = "[author23 post's body]", BlogId = 2, Category = "Books"},
                new Post(){ Id = 4, PostTitle = "[author26 post's title]", PostAuthor = "author26", PostBody = "[author26 post's body]", BlogId = 5, Category = "Fitness"},
                new Post(){ Id = 5, PostTitle = "[author4 post's title]", PostAuthor = "author4", PostBody = "[author4 post's body]", BlogId = 7, Category = "Business"},
                new Post(){ Id = 6, PostTitle = "[author29 post's title]", PostAuthor = "author29", PostBody = "[author29 post's body]", BlogId = 7, Category = "Food"},
                new Post(){ Id = 7, PostTitle = "[author27 post's title]", PostAuthor = "author27", PostBody = "[author27 post's body]", BlogId = 5, Category = "Parenting"},
                new Post(){ Id = 8, PostTitle = "[author7 post's title]", PostAuthor = "author7", PostBody = "[author7 post's body]", BlogId = 2, Category = "Sports"},
                new Post(){ Id = 9, PostTitle = "[author28 post's title]", PostAuthor = "author28", PostBody = "[author28 post's body]", BlogId = 6, Category = "Gaming"},
                new Post(){ Id = 10, PostTitle = "[author17 post's title]", PostAuthor = "author17", PostBody = "[author17 post's body]", BlogId = 10, Category = "Art"},
                new Post(){ Id = 11, PostTitle = "[author26 post's title]", PostAuthor = "author26", PostBody = "[author26 post's body]", BlogId = 3, Category = "Science"},
                new Post(){ Id = 12, PostTitle = "[author21 post's title]", PostAuthor = "author21", PostBody = "[author21 post's body]", BlogId = 10, Category = "Art"},
                new Post(){ Id = 13, PostTitle = "[author20 post's title]", PostAuthor = "author20", PostBody = "[author20 post's body]", BlogId = 7, Category = "Food"},
                new Post(){ Id = 14, PostTitle = "[author5 post's title]", PostAuthor = "author5", PostBody = "[author5 post's body]", BlogId = 2, Category = "Gaming"},
                new Post(){ Id = 15, PostTitle = "[author3 post's title]", PostAuthor = "author3", PostBody = "[author3 post's body]", BlogId = 5, Category = "Health"},
                new Post(){ Id = 16, PostTitle = "[author7 post's title]", PostAuthor = "author7", PostBody = "[author7 post's body]", BlogId = 7, Category = "Fashion"},
                new Post(){ Id = 17, PostTitle = "[author14 post's title]", PostAuthor = "author14", PostBody = "[author14 post's body]", BlogId = 6, Category = "DIY"},
                new Post(){ Id = 18, PostTitle = "[author2 post's title]", PostAuthor = "author2", PostBody = "[author2 post's body]", BlogId = 6, Category = "Technology"},
                new Post(){ Id = 19, PostTitle = "[author18 post's title]", PostAuthor = "author18", PostBody = "[author18 post's body]", BlogId = 6, Category = "Education"},
                new Post(){ Id = 20, PostTitle = "[author13 post's title]", PostAuthor = "author13", PostBody = "[author13 post's body]", BlogId = 1, Category = "Food"},
                new Post(){ Id = 21, PostTitle = "[author16 post's title]", PostAuthor = "author16", PostBody = "[author16 post's body]", BlogId = 10, Category = "Health"},
                new Post(){ Id = 22, PostTitle = "[author10 post's title]", PostAuthor = "author10", PostBody = "[author10 post's body]", BlogId = 5, Category = "Books"},
                new Post(){ Id = 23, PostTitle = "[author6 post's title]", PostAuthor = "author6", PostBody = "[author6 post's body]", BlogId = 2, Category = "Music"},
                new Post(){ Id = 24, PostTitle = "[author13 post's title]", PostAuthor = "author13", PostBody = "[author13 post's body]", BlogId = 1, Category = "DIY"},
                new Post(){ Id = 25, PostTitle = "[author9 post's title]", PostAuthor = "author9", PostBody = "[author9 post's body]", BlogId = 8, Category = "Technology"},
                new Post(){ Id = 26, PostTitle = "[author26 post's title]", PostAuthor = "author26", PostBody = "[author26 post's body]", BlogId = 2, Category = "Science"},
                new Post(){ Id = 27, PostTitle = "[author27 post's title]", PostAuthor = "author27", PostBody = "[author27 post's body]", BlogId = 4, Category = "Art"},
                new Post(){ Id = 28, PostTitle = "[author8 post's title]", PostAuthor = "author8", PostBody = "[author8 post's body]", BlogId = 10, Category = "Health"},
                new Post(){ Id = 29, PostTitle = "[author4 post's title]", PostAuthor = "author4", PostBody = "[author4 post's body]", BlogId = 8, Category = "Fitness"},
                new Post(){ Id = 30, PostTitle = "[author26 post's title]", PostAuthor = "author26", PostBody = "[author26 post's body]", BlogId = 9, Category = "Books"},
                new Post(){ Id = 31, PostTitle = "[author8 post's title]", PostAuthor = "author8", PostBody = "[author8 post's body]", BlogId = 4, Category = "Business"},
                new Post(){ Id = 32, PostTitle = "[author19 post's title]", PostAuthor = "author19", PostBody = "[author19 post's body]", BlogId = 10, Category = "Travel"},
                new Post(){ Id = 33, PostTitle = "[author5 post's title]", PostAuthor = "author5", PostBody = "[author5 post's body]", BlogId = 1, Category = "Fitness"},
                new Post(){ Id = 34, PostTitle = "[author25 post's title]", PostAuthor = "author25", PostBody = "[author25 post's body]", BlogId = 3, Category = "DIY"},
                new Post(){ Id = 35, PostTitle = "[author3 post's title]", PostAuthor = "author3", PostBody = "[author3 post's body]", BlogId = 9, Category = "Technology"},
                new Post(){ Id = 36, PostTitle = "[author3 post's title]", PostAuthor = "author3", PostBody = "[author3 post's body]", BlogId = 8, Category = "Business"},
                new Post(){ Id = 37, PostTitle = "[author18 post's title]", PostAuthor = "author18", PostBody = "[author18 post's body]", BlogId = 8, Category = "Science"},
                new Post(){ Id = 38, PostTitle = "[author4 post's title]", PostAuthor = "author4", PostBody = "[author4 post's body]", BlogId = 2, Category = "Music"},
                new Post(){ Id = 39, PostTitle = "[author8 post's title]", PostAuthor = "author8", PostBody = "[author8 post's body]", BlogId = 5, Category = "Photography"},
                new Post(){ Id = 40, PostTitle = "[author26 post's title]", PostAuthor = "author26", PostBody = "[author26 post's body]", BlogId = 10, Category = "Health"},
                new Post(){ Id = 41, PostTitle = "[author2 post's title]", PostAuthor = "author2", PostBody = "[author2 post's body]", BlogId = 8, Category = "Parenting"},
                new Post(){ Id = 42, PostTitle = "[author17 post's title]", PostAuthor = "author17", PostBody = "[author17 post's body]", BlogId = 10, Category = "Finance"},
                new Post(){ Id = 43, PostTitle = "[author20 post's title]", PostAuthor = "author20", PostBody = "[author20 post's body]", BlogId = 4, Category = "Finance"},
                new Post(){ Id = 44, PostTitle = "[author6 post's title]", PostAuthor = "author6", PostBody = "[author6 post's body]", BlogId = 1, Category = "Fitness"},
                new Post(){ Id = 45, PostTitle = "[author2 post's title]", PostAuthor = "author2", PostBody = "[author2 post's body]", BlogId = 6, Category = "Art"},
                new Post(){ Id = 46, PostTitle = "[author4 post's title]", PostAuthor = "author4", PostBody = "[author4 post's body]", BlogId = 3, Category = "Music"},
                new Post(){ Id = 47, PostTitle = "[author9 post's title]", PostAuthor = "author9", PostBody = "[author9 post's body]", BlogId = 9, Category = "Education"},
                new Post(){ Id = 48, PostTitle = "[author29 post's title]", PostAuthor = "author29", PostBody = "[author29 post's body]", BlogId = 9, Category = "Business"},
                new Post(){ Id = 49, PostTitle = "[author1 post's title]", PostAuthor = "author1", PostBody = "[author1 post's body]", BlogId = 7, Category = "Photography"},
                new Post(){ Id = 50, PostTitle = "[author4 post's title]", PostAuthor = "author4", PostBody = "[author4 post's body]", BlogId = 5, Category = "Sports"},
                new Post(){ Id = 51, PostTitle = "[author9 post's title]", PostAuthor = "author9", PostBody = "[author9 post's body]", BlogId = 1, Category = "Technology"},
                new Post(){ Id = 52, PostTitle = "[author6 post's title]", PostAuthor = "author6", PostBody = "[author6 post's body]", BlogId = 10, Category = "Technology"},
                new Post(){ Id = 53, PostTitle = "[author8 post's title]", PostAuthor = "author8", PostBody = "[author8 post's body]", BlogId = 1, Category = "Technology"},
                new Post(){ Id = 54, PostTitle = "[author1 post's title]", PostAuthor = "author1", PostBody = "[author1 post's body]", BlogId = 3, Category = "Education"},
                new Post(){ Id = 55, PostTitle = "[author20 post's title]", PostAuthor = "author20", PostBody = "[author20 post's body]", BlogId = 9, Category = "Business"},
                new Post(){ Id = 56, PostTitle = "[author15 post's title]", PostAuthor = "author15", PostBody = "[author15 post's body]", BlogId = 5, Category = "Art"},
                new Post(){ Id = 57, PostTitle = "[author9 post's title]", PostAuthor = "author9", PostBody = "[author9 post's body]", BlogId = 5, Category = "Sports"},
                new Post(){ Id = 58, PostTitle = "[author14 post's title]", PostAuthor = "author14", PostBody = "[author14 post's body]", BlogId = 7, Category = "Art"},
                new Post(){ Id = 59, PostTitle = "[author26 post's title]", PostAuthor = "author26", PostBody = "[author26 post's body]", BlogId = 8, Category = "Food"},
                new Post(){ Id = 60, PostTitle = "[author15 post's title]", PostAuthor = "author15", PostBody = "[author15 post's body]", BlogId = 4, Category = "Sports"}
            };
            List<Comment> comments = new List<Comment>()
            {
                new Comment(){ Id = 1, UserName = "user326", CommentBody = "[user326 comment's about author24 post's]", PostId = 1, PostRating = 9},
                new Comment(){ Id = 2, UserName = "user451", CommentBody = "[user451 comment's about author24 post's]", PostId = 1, PostRating = 4},
                new Comment(){ Id = 3, UserName = "user627", CommentBody = "[user627 comment's about author24 post's]", PostId = 1, PostRating = 4},
                new Comment(){ Id = 4, UserName = "user80", CommentBody = "[user80 comment's about author24 post's]", PostId = 1, PostRating = 3},
                new Comment(){ Id = 5, UserName = "user104", CommentBody = "[user104 comment's about author24 post's]", PostId = 1, PostRating = 1},
                new Comment(){ Id = 6, UserName = "user80", CommentBody = "[user80 comment's about author24 post's]", PostId = 1, PostRating = 8},
                new Comment(){ Id = 7, UserName = "user430", CommentBody = "[user430 comment's about author24 post's]", PostId = 1, PostRating = 3},
                new Comment(){ Id = 8, UserName = "user140", CommentBody = "[user140 comment's about author24 post's]", PostId = 1, PostRating = 7},
                new Comment(){ Id = 9, UserName = "user684", CommentBody = "[user684 comment's about author2 post's]", PostId = 2, PostRating = 8},
                new Comment(){ Id = 10, UserName = "user385", CommentBody = "[user385 comment's about author2 post's]", PostId = 2, PostRating = 1},
                new Comment(){ Id = 11, UserName = "user643", CommentBody = "[user643 comment's about author2 post's]", PostId = 2, PostRating = 3},
                new Comment(){ Id = 12, UserName = "user483", CommentBody = "[user483 comment's about author2 post's]", PostId = 2, PostRating = 3},
                new Comment(){ Id = 13, UserName = "user252", CommentBody = "[user252 comment's about author2 post's]", PostId = 2, PostRating = 8},
                new Comment(){ Id = 14, UserName = "user259", CommentBody = "[user259 comment's about author2 post's]", PostId = 2, PostRating = 1},
                new Comment(){ Id = 15, UserName = "user398", CommentBody = "[user398 comment's about author2 post's]", PostId = 2, PostRating = 6},
                new Comment(){ Id = 16, UserName = "user490", CommentBody = "[user490 comment's about author3 post's]", PostId = 3, PostRating = 9},
                new Comment(){ Id = 17, UserName = "user229", CommentBody = "[user229 comment's about author3 post's]", PostId = 3, PostRating = 4},
                new Comment(){ Id = 18, UserName = "user214", CommentBody = "[user214 comment's about author3 post's]", PostId = 3, PostRating = 1},
                new Comment(){ Id = 19, UserName = "user313", CommentBody = "[user313 comment's about author3 post's]", PostId = 3, PostRating = 1},
                new Comment(){ Id = 20, UserName = "user521", CommentBody = "[user521 comment's about author3 post's]", PostId = 3, PostRating = 9},
                new Comment(){ Id = 21, UserName = "user125", CommentBody = "[user125 comment's about author3 post's]", PostId = 3, PostRating = 6},
                new Comment(){ Id = 22, UserName = "user123", CommentBody = "[user123 comment's about author3 post's]", PostId = 3, PostRating = 9},
                new Comment(){ Id = 23, UserName = "user645", CommentBody = "[user645 comment's about author3 post's]", PostId = 3, PostRating = 9},
                new Comment(){ Id = 24, UserName = "user302", CommentBody = "[user302 comment's about author3 post's]", PostId = 3, PostRating = 2},
                new Comment(){ Id = 25, UserName = "user443", CommentBody = "[user443 comment's about author3 post's]", PostId = 3, PostRating = 9},
                new Comment(){ Id = 26, UserName = "user620", CommentBody = "[user620 comment's about author3 post's]", PostId = 3, PostRating = 4},
                new Comment(){ Id = 27, UserName = "user106", CommentBody = "[user106 comment's about author3 post's]", PostId = 3, PostRating = 3},
                new Comment(){ Id = 28, UserName = "user457", CommentBody = "[user457 comment's about author3 post's]", PostId = 3, PostRating = 1},
                new Comment(){ Id = 29, UserName = "user357", CommentBody = "[user357 comment's about author4 post's]", PostId = 4, PostRating = 2},
                new Comment(){ Id = 30, UserName = "user279", CommentBody = "[user279 comment's about author4 post's]", PostId = 4, PostRating = 4},
                new Comment(){ Id = 31, UserName = "user384", CommentBody = "[user384 comment's about author4 post's]", PostId = 4, PostRating = 6},
                new Comment(){ Id = 32, UserName = "user256", CommentBody = "[user256 comment's about author4 post's]", PostId = 4, PostRating = 5},
                new Comment(){ Id = 33, UserName = "user544", CommentBody = "[user544 comment's about author4 post's]", PostId = 4, PostRating = 9},
                new Comment(){ Id = 34, UserName = "user626", CommentBody = "[user626 comment's about author4 post's]", PostId = 4, PostRating = 2},
                new Comment(){ Id = 35, UserName = "user470", CommentBody = "[user470 comment's about author4 post's]", PostId = 4, PostRating = 1},
                new Comment(){ Id = 36, UserName = "user393", CommentBody = "[user393 comment's about author4 post's]", PostId = 4, PostRating = 7},
                new Comment(){ Id = 37, UserName = "user465", CommentBody = "[user465 comment's about author4 post's]", PostId = 4, PostRating = 6},
                new Comment(){ Id = 38, UserName = "user368", CommentBody = "[user368 comment's about author4 post's]", PostId = 4, PostRating = 5},
                new Comment(){ Id = 39, UserName = "user698", CommentBody = "[user698 comment's about author4 post's]", PostId = 4, PostRating = 9},
                new Comment(){ Id = 40, UserName = "user580", CommentBody = "[user580 comment's about author4 post's]", PostId = 4, PostRating = 5},
                new Comment(){ Id = 41, UserName = "user502", CommentBody = "[user502 comment's about author4 post's]", PostId = 4, PostRating = 8},
                new Comment(){ Id = 42, UserName = "user90", CommentBody = "[user90 comment's about author14 post's]", PostId = 5, PostRating = 4},
                new Comment(){ Id = 43, UserName = "user421", CommentBody = "[user421 comment's about author14 post's]", PostId = 5, PostRating = 7},
                new Comment(){ Id = 44, UserName = "user140", CommentBody = "[user140 comment's about author14 post's]", PostId = 5, PostRating = 9},
                new Comment(){ Id = 45, UserName = "user327", CommentBody = "[user327 comment's about author14 post's]", PostId = 5, PostRating = 8},
                new Comment(){ Id = 46, UserName = "user664", CommentBody = "[user664 comment's about author14 post's]", PostId = 5, PostRating = 5},
                new Comment(){ Id = 47, UserName = "user94", CommentBody = "[user94 comment's about author21 post's]", PostId = 6, PostRating = 1},
                new Comment(){ Id = 48, UserName = "user427", CommentBody = "[user427 comment's about author21 post's]", PostId = 6, PostRating = 1},
                new Comment(){ Id = 49, UserName = "user344", CommentBody = "[user344 comment's about author21 post's]", PostId = 6, PostRating = 7},
                new Comment(){ Id = 50, UserName = "user261", CommentBody = "[user261 comment's about author21 post's]", PostId = 6, PostRating = 4},
                new Comment(){ Id = 51, UserName = "user435", CommentBody = "[user435 comment's about author21 post's]", PostId = 6, PostRating = 8},
                new Comment(){ Id = 52, UserName = "user642", CommentBody = "[user642 comment's about author19 post's]", PostId = 7, PostRating = 3},
                new Comment(){ Id = 53, UserName = "user441", CommentBody = "[user441 comment's about author19 post's]", PostId = 7, PostRating = 6},
                new Comment(){ Id = 54, UserName = "user621", CommentBody = "[user621 comment's about author19 post's]", PostId = 7, PostRating = 4},
                new Comment(){ Id = 55, UserName = "user173", CommentBody = "[user173 comment's about author19 post's]", PostId = 7, PostRating = 7},
                new Comment(){ Id = 56, UserName = "user447", CommentBody = "[user447 comment's about author19 post's]", PostId = 7, PostRating = 9},
                new Comment(){ Id = 57, UserName = "user594", CommentBody = "[user594 comment's about author19 post's]", PostId = 7, PostRating = 4},
                new Comment(){ Id = 58, UserName = "user609", CommentBody = "[user609 comment's about author19 post's]", PostId = 7, PostRating = 2},
                new Comment(){ Id = 59, UserName = "user241", CommentBody = "[user241 comment's about author19 post's]", PostId = 7, PostRating = 4},
                new Comment(){ Id = 60, UserName = "user423", CommentBody = "[user423 comment's about author19 post's]", PostId = 7, PostRating = 9},
                new Comment(){ Id = 61, UserName = "user540", CommentBody = "[user540 comment's about author8 post's]", PostId = 8, PostRating = 4},
                new Comment(){ Id = 62, UserName = "user428", CommentBody = "[user428 comment's about author8 post's]", PostId = 8, PostRating = 7},
                new Comment(){ Id = 63, UserName = "user316", CommentBody = "[user316 comment's about author8 post's]", PostId = 8, PostRating = 6},
                new Comment(){ Id = 64, UserName = "user193", CommentBody = "[user193 comment's about author8 post's]", PostId = 8, PostRating = 5},
                new Comment(){ Id = 65, UserName = "user426", CommentBody = "[user426 comment's about author8 post's]", PostId = 8, PostRating = 5},
                new Comment(){ Id = 66, UserName = "user553", CommentBody = "[user553 comment's about author8 post's]", PostId = 8, PostRating = 3},
                new Comment(){ Id = 67, UserName = "user173", CommentBody = "[user173 comment's about author28 post's]", PostId = 9, PostRating = 4},
                new Comment(){ Id = 68, UserName = "user617", CommentBody = "[user617 comment's about author28 post's]", PostId = 9, PostRating = 5},
                new Comment(){ Id = 69, UserName = "user514", CommentBody = "[user514 comment's about author28 post's]", PostId = 9, PostRating = 3},
                new Comment(){ Id = 70, UserName = "user574", CommentBody = "[user574 comment's about author28 post's]", PostId = 9, PostRating = 8},
                new Comment(){ Id = 71, UserName = "user660", CommentBody = "[user660 comment's about author28 post's]", PostId = 9, PostRating = 8},
                new Comment(){ Id = 72, UserName = "user295", CommentBody = "[user295 comment's about author28 post's]", PostId = 9, PostRating = 7},
                new Comment(){ Id = 73, UserName = "user112", CommentBody = "[user112 comment's about author28 post's]", PostId = 10, PostRating = 4},
                new Comment(){ Id = 74, UserName = "user342", CommentBody = "[user342 comment's about author28 post's]", PostId = 10, PostRating = 4},
                new Comment(){ Id = 75, UserName = "user699", CommentBody = "[user699 comment's about author28 post's]", PostId = 10, PostRating = 1},
                new Comment(){ Id = 76, UserName = "user673", CommentBody = "[user673 comment's about author28 post's]", PostId = 10, PostRating = 9},
                new Comment(){ Id = 77, UserName = "user153", CommentBody = "[user153 comment's about author28 post's]", PostId = 10, PostRating = 4},
                new Comment(){ Id = 78, UserName = "user606", CommentBody = "[user606 comment's about author28 post's]", PostId = 10, PostRating = 3},
                new Comment(){ Id = 79, UserName = "user663", CommentBody = "[user663 comment's about author28 post's]", PostId = 10, PostRating = 8},
                new Comment(){ Id = 80, UserName = "user520", CommentBody = "[user520 comment's about author28 post's]", PostId = 10, PostRating = 1},
                new Comment(){ Id = 81, UserName = "user319", CommentBody = "[user319 comment's about author17 post's]", PostId = 11, PostRating = 8},
                new Comment(){ Id = 82, UserName = "user587", CommentBody = "[user587 comment's about author17 post's]", PostId = 11, PostRating = 6},
                new Comment(){ Id = 83, UserName = "user241", CommentBody = "[user241 comment's about author17 post's]", PostId = 11, PostRating = 2},
                new Comment(){ Id = 84, UserName = "user397", CommentBody = "[user397 comment's about author29 post's]", PostId = 12, PostRating = 2},
                new Comment(){ Id = 85, UserName = "user348", CommentBody = "[user348 comment's about author29 post's]", PostId = 12, PostRating = 6},
                new Comment(){ Id = 86, UserName = "user354", CommentBody = "[user354 comment's about author29 post's]", PostId = 12, PostRating = 4},
                new Comment(){ Id = 87, UserName = "user662", CommentBody = "[user662 comment's about author29 post's]", PostId = 12, PostRating = 5},
                new Comment(){ Id = 88, UserName = "user650", CommentBody = "[user650 comment's about author29 post's]", PostId = 12, PostRating = 4},
                new Comment(){ Id = 89, UserName = "user278", CommentBody = "[user278 comment's about author29 post's]", PostId = 12, PostRating = 6},
                new Comment(){ Id = 90, UserName = "user695", CommentBody = "[user695 comment's about author29 post's]", PostId = 12, PostRating = 3},
                new Comment(){ Id = 91, UserName = "user534", CommentBody = "[user534 comment's about author20 post's]", PostId = 13, PostRating = 9},
                new Comment(){ Id = 92, UserName = "user551", CommentBody = "[user551 comment's about author20 post's]", PostId = 13, PostRating = 8},
                new Comment(){ Id = 93, UserName = "user533", CommentBody = "[user533 comment's about author20 post's]", PostId = 13, PostRating = 4},
                new Comment(){ Id = 94, UserName = "user81", CommentBody = "[user81 comment's about author20 post's]", PostId = 13, PostRating = 6},
                new Comment(){ Id = 95, UserName = "user537", CommentBody = "[user537 comment's about author20 post's]", PostId = 13, PostRating = 9},
                new Comment(){ Id = 96, UserName = "user350", CommentBody = "[user350 comment's about author20 post's]", PostId = 13, PostRating = 4},
                new Comment(){ Id = 97, UserName = "user599", CommentBody = "[user599 comment's about author20 post's]", PostId = 13, PostRating = 3},
                new Comment(){ Id = 98, UserName = "user503", CommentBody = "[user503 comment's about author20 post's]", PostId = 13, PostRating = 8},
                new Comment(){ Id = 99, UserName = "user598", CommentBody = "[user598 comment's about author20 post's]", PostId = 13, PostRating = 4},
                new Comment(){ Id = 100, UserName = "user238", CommentBody = "[user238 comment's about author19 post's]", PostId = 14, PostRating = 7},
                new Comment(){ Id = 101, UserName = "user587", CommentBody = "[user587 comment's about author19 post's]", PostId = 14, PostRating = 7},
                new Comment(){ Id = 102, UserName = "user466", CommentBody = "[user466 comment's about author19 post's]", PostId = 14, PostRating = 1},
                new Comment(){ Id = 103, UserName = "user577", CommentBody = "[user577 comment's about author19 post's]", PostId = 14, PostRating = 7},
                new Comment(){ Id = 104, UserName = "user257", CommentBody = "[user257 comment's about author19 post's]", PostId = 14, PostRating = 8},
                new Comment(){ Id = 105, UserName = "user504", CommentBody = "[user504 comment's about author26 post's]", PostId = 15, PostRating = 2},
                new Comment(){ Id = 106, UserName = "user537", CommentBody = "[user537 comment's about author26 post's]", PostId = 15, PostRating = 4},
                new Comment(){ Id = 107, UserName = "user84", CommentBody = "[user84 comment's about author26 post's]", PostId = 15, PostRating = 2},
                new Comment(){ Id = 108, UserName = "user333", CommentBody = "[user333 comment's about author26 post's]", PostId = 15, PostRating = 2},
                new Comment(){ Id = 109, UserName = "user352", CommentBody = "[user352 comment's about author3 post's]", PostId = 16, PostRating = 4},
                new Comment(){ Id = 110, UserName = "user87", CommentBody = "[user87 comment's about author3 post's]", PostId = 16, PostRating = 1},
                new Comment(){ Id = 111, UserName = "user378", CommentBody = "[user378 comment's about author3 post's]", PostId = 16, PostRating = 2},
                new Comment(){ Id = 112, UserName = "user665", CommentBody = "[user665 comment's about author3 post's]", PostId = 16, PostRating = 4},
                new Comment(){ Id = 113, UserName = "user129", CommentBody = "[user129 comment's about author3 post's]", PostId = 16, PostRating = 7},
                new Comment(){ Id = 114, UserName = "user182", CommentBody = "[user182 comment's about author3 post's]", PostId = 16, PostRating = 4},
                new Comment(){ Id = 115, UserName = "user316", CommentBody = "[user316 comment's about author3 post's]", PostId = 16, PostRating = 7},
                new Comment(){ Id = 116, UserName = "user198", CommentBody = "[user198 comment's about author1 post's]", PostId = 17, PostRating = 7},
                new Comment(){ Id = 117, UserName = "user438", CommentBody = "[user438 comment's about author1 post's]", PostId = 17, PostRating = 7},
                new Comment(){ Id = 118, UserName = "user605", CommentBody = "[user605 comment's about author1 post's]", PostId = 17, PostRating = 2},
                new Comment(){ Id = 119, UserName = "user476", CommentBody = "[user476 comment's about author1 post's]", PostId = 17, PostRating = 5},
                new Comment(){ Id = 120, UserName = "user159", CommentBody = "[user159 comment's about author1 post's]", PostId = 17, PostRating = 7},
                new Comment(){ Id = 121, UserName = "user462", CommentBody = "[user462 comment's about author1 post's]", PostId = 17, PostRating = 9},
                new Comment(){ Id = 122, UserName = "user183", CommentBody = "[user183 comment's about author14 post's]", PostId = 18, PostRating = 9},
                new Comment(){ Id = 123, UserName = "user490", CommentBody = "[user490 comment's about author14 post's]", PostId = 18, PostRating = 6},
                new Comment(){ Id = 124, UserName = "user370", CommentBody = "[user370 comment's about author14 post's]", PostId = 18, PostRating = 1},
                new Comment(){ Id = 125, UserName = "user307", CommentBody = "[user307 comment's about author14 post's]", PostId = 18, PostRating = 4},
                new Comment(){ Id = 126, UserName = "user600", CommentBody = "[user600 comment's about author14 post's]", PostId = 18, PostRating = 1},
                new Comment(){ Id = 127, UserName = "user395", CommentBody = "[user395 comment's about author14 post's]", PostId = 18, PostRating = 8},
                new Comment(){ Id = 128, UserName = "user380", CommentBody = "[user380 comment's about author14 post's]", PostId = 18, PostRating = 4},
                new Comment(){ Id = 129, UserName = "user93", CommentBody = "[user93 comment's about author14 post's]", PostId = 18, PostRating = 9},
                new Comment(){ Id = 130, UserName = "user212", CommentBody = "[user212 comment's about author14 post's]", PostId = 18, PostRating = 8},
                new Comment(){ Id = 131, UserName = "user97", CommentBody = "[user97 comment's about author14 post's]", PostId = 18, PostRating = 4},
                new Comment(){ Id = 132, UserName = "user393", CommentBody = "[user393 comment's about author14 post's]", PostId = 18, PostRating = 1},
                new Comment(){ Id = 133, UserName = "user73", CommentBody = "[user73 comment's about author6 post's]", PostId = 19, PostRating = 1},
                new Comment(){ Id = 134, UserName = "user457", CommentBody = "[user457 comment's about author6 post's]", PostId = 19, PostRating = 5},
                new Comment(){ Id = 135, UserName = "user123", CommentBody = "[user123 comment's about author6 post's]", PostId = 19, PostRating = 4},
                new Comment(){ Id = 136, UserName = "user606", CommentBody = "[user606 comment's about author6 post's]", PostId = 19, PostRating = 8},
                new Comment(){ Id = 137, UserName = "user282", CommentBody = "[user282 comment's about author6 post's]", PostId = 19, PostRating = 4},
                new Comment(){ Id = 138, UserName = "user655", CommentBody = "[user655 comment's about author6 post's]", PostId = 20, PostRating = 5},
                new Comment(){ Id = 139, UserName = "user548", CommentBody = "[user548 comment's about author6 post's]", PostId = 20, PostRating = 5},
                new Comment(){ Id = 140, UserName = "user456", CommentBody = "[user456 comment's about author6 post's]", PostId = 20, PostRating = 7},
                new Comment(){ Id = 141, UserName = "user238", CommentBody = "[user238 comment's about author6 post's]", PostId = 20, PostRating = 3},
                new Comment(){ Id = 142, UserName = "user430", CommentBody = "[user430 comment's about author6 post's]", PostId = 20, PostRating = 3},
                new Comment(){ Id = 143, UserName = "user548", CommentBody = "[user548 comment's about author6 post's]", PostId = 20, PostRating = 3},
                new Comment(){ Id = 144, UserName = "user571", CommentBody = "[user571 comment's about author6 post's]", PostId = 20, PostRating = 1},
                new Comment(){ Id = 145, UserName = "user624", CommentBody = "[user624 comment's about author6 post's]", PostId = 20, PostRating = 1},
                new Comment(){ Id = 146, UserName = "user673", CommentBody = "[user673 comment's about author6 post's]", PostId = 20, PostRating = 7},
                new Comment(){ Id = 147, UserName = "user97", CommentBody = "[user97 comment's about author1 post's]", PostId = 21, PostRating = 7},
                new Comment(){ Id = 148, UserName = "user533", CommentBody = "[user533 comment's about author1 post's]", PostId = 21, PostRating = 3},
                new Comment(){ Id = 149, UserName = "user236", CommentBody = "[user236 comment's about author1 post's]", PostId = 21, PostRating = 3},
                new Comment(){ Id = 150, UserName = "user626", CommentBody = "[user626 comment's about author1 post's]", PostId = 21, PostRating = 5},
                new Comment(){ Id = 151, UserName = "user96", CommentBody = "[user96 comment's about author1 post's]", PostId = 21, PostRating = 5},
                new Comment(){ Id = 152, UserName = "user191", CommentBody = "[user191 comment's about author1 post's]", PostId = 21, PostRating = 5},
                new Comment(){ Id = 153, UserName = "user481", CommentBody = "[user481 comment's about author1 post's]", PostId = 21, PostRating = 8},
                new Comment(){ Id = 154, UserName = "user227", CommentBody = "[user227 comment's about author1 post's]", PostId = 21, PostRating = 4},
                new Comment(){ Id = 155, UserName = "user596", CommentBody = "[user596 comment's about author2 post's]", PostId = 22, PostRating = 1},
                new Comment(){ Id = 156, UserName = "user260", CommentBody = "[user260 comment's about author2 post's]", PostId = 22, PostRating = 5},
                new Comment(){ Id = 157, UserName = "user167", CommentBody = "[user167 comment's about author2 post's]", PostId = 22, PostRating = 9},
                new Comment(){ Id = 158, UserName = "user363", CommentBody = "[user363 comment's about author2 post's]", PostId = 22, PostRating = 6},
                new Comment(){ Id = 159, UserName = "user680", CommentBody = "[user680 comment's about author2 post's]", PostId = 22, PostRating = 5},
                new Comment(){ Id = 160, UserName = "user179", CommentBody = "[user179 comment's about author2 post's]", PostId = 22, PostRating = 3},
                new Comment(){ Id = 161, UserName = "user67", CommentBody = "[user67 comment's about author2 post's]", PostId = 22, PostRating = 9},
                new Comment(){ Id = 162, UserName = "user372", CommentBody = "[user372 comment's about author2 post's]", PostId = 22, PostRating = 8},
                new Comment(){ Id = 163, UserName = "user494", CommentBody = "[user494 comment's about author2 post's]", PostId = 22, PostRating = 5},
                new Comment(){ Id = 164, UserName = "user569", CommentBody = "[user569 comment's about author2 post's]", PostId = 22, PostRating = 4},
                new Comment(){ Id = 165, UserName = "user304", CommentBody = "[user304 comment's about author21 post's]", PostId = 23, PostRating = 2},
                new Comment(){ Id = 166, UserName = "user184", CommentBody = "[user184 comment's about author21 post's]", PostId = 23, PostRating = 7},
                new Comment(){ Id = 167, UserName = "user264", CommentBody = "[user264 comment's about author21 post's]", PostId = 23, PostRating = 3},
                new Comment(){ Id = 168, UserName = "user67", CommentBody = "[user67 comment's about author21 post's]", PostId = 23, PostRating = 8},
                new Comment(){ Id = 169, UserName = "user641", CommentBody = "[user641 comment's about author21 post's]", PostId = 23, PostRating = 9},
                new Comment(){ Id = 170, UserName = "user146", CommentBody = "[user146 comment's about author21 post's]", PostId = 23, PostRating = 9},
                new Comment(){ Id = 171, UserName = "user264", CommentBody = "[user264 comment's about author21 post's]", PostId = 23, PostRating = 9},
                new Comment(){ Id = 172, UserName = "user679", CommentBody = "[user679 comment's about author10 post's]", PostId = 24, PostRating = 9},
                new Comment(){ Id = 173, UserName = "user367", CommentBody = "[user367 comment's about author10 post's]", PostId = 24, PostRating = 2},
                new Comment(){ Id = 174, UserName = "user541", CommentBody = "[user541 comment's about author10 post's]", PostId = 24, PostRating = 5},
                new Comment(){ Id = 175, UserName = "user114", CommentBody = "[user114 comment's about author10 post's]", PostId = 24, PostRating = 5},
                new Comment(){ Id = 176, UserName = "user131", CommentBody = "[user131 comment's about author10 post's]", PostId = 24, PostRating = 8},
                new Comment(){ Id = 177, UserName = "user468", CommentBody = "[user468 comment's about author10 post's]", PostId = 24, PostRating = 5},
                new Comment(){ Id = 178, UserName = "user572", CommentBody = "[user572 comment's about author10 post's]", PostId = 24, PostRating = 6},
                new Comment(){ Id = 179, UserName = "user145", CommentBody = "[user145 comment's about author18 post's]", PostId = 25, PostRating = 3},
                new Comment(){ Id = 180, UserName = "user500", CommentBody = "[user500 comment's about author18 post's]", PostId = 25, PostRating = 4},
                new Comment(){ Id = 181, UserName = "user619", CommentBody = "[user619 comment's about author18 post's]", PostId = 25, PostRating = 2},
                new Comment(){ Id = 182, UserName = "user568", CommentBody = "[user568 comment's about author18 post's]", PostId = 25, PostRating = 8},
                new Comment(){ Id = 183, UserName = "user581", CommentBody = "[user581 comment's about author18 post's]", PostId = 25, PostRating = 8},
                new Comment(){ Id = 184, UserName = "user131", CommentBody = "[user131 comment's about author18 post's]", PostId = 25, PostRating = 1},
                new Comment(){ Id = 185, UserName = "user613", CommentBody = "[user613 comment's about author18 post's]", PostId = 25, PostRating = 2},
                new Comment(){ Id = 186, UserName = "user438", CommentBody = "[user438 comment's about author24 post's]", PostId = 26, PostRating = 8},
                new Comment(){ Id = 187, UserName = "user337", CommentBody = "[user337 comment's about author24 post's]", PostId = 26, PostRating = 5},
                new Comment(){ Id = 188, UserName = "user322", CommentBody = "[user322 comment's about author24 post's]", PostId = 26, PostRating = 3},
                new Comment(){ Id = 189, UserName = "user687", CommentBody = "[user687 comment's about author24 post's]", PostId = 26, PostRating = 5},
                new Comment(){ Id = 190, UserName = "user572", CommentBody = "[user572 comment's about author24 post's]", PostId = 26, PostRating = 1},
                new Comment(){ Id = 191, UserName = "user405", CommentBody = "[user405 comment's about author18 post's]", PostId = 27, PostRating = 7},
                new Comment(){ Id = 192, UserName = "user457", CommentBody = "[user457 comment's about author18 post's]", PostId = 27, PostRating = 6},
                new Comment(){ Id = 193, UserName = "user161", CommentBody = "[user161 comment's about author18 post's]", PostId = 27, PostRating = 2},
                new Comment(){ Id = 194, UserName = "user644", CommentBody = "[user644 comment's about author18 post's]", PostId = 27, PostRating = 1},
                new Comment(){ Id = 195, UserName = "user535", CommentBody = "[user535 comment's about author18 post's]", PostId = 27, PostRating = 5},
                new Comment(){ Id = 196, UserName = "user591", CommentBody = "[user591 comment's about author18 post's]", PostId = 27, PostRating = 2},
                new Comment(){ Id = 197, UserName = "user546", CommentBody = "[user546 comment's about author18 post's]", PostId = 27, PostRating = 1},
                new Comment(){ Id = 198, UserName = "user286", CommentBody = "[user286 comment's about author18 post's]", PostId = 27, PostRating = 7},
                new Comment(){ Id = 199, UserName = "user628", CommentBody = "[user628 comment's about author18 post's]", PostId = 27, PostRating = 7},
                new Comment(){ Id = 200, UserName = "user182", CommentBody = "[user182 comment's about author18 post's]", PostId = 27, PostRating = 4},
                new Comment(){ Id = 201, UserName = "user448", CommentBody = "[user448 comment's about author18 post's]", PostId = 27, PostRating = 5},
                new Comment(){ Id = 202, UserName = "user193", CommentBody = "[user193 comment's about author14 post's]", PostId = 28, PostRating = 8},
                new Comment(){ Id = 203, UserName = "user238", CommentBody = "[user238 comment's about author14 post's]", PostId = 28, PostRating = 2},
                new Comment(){ Id = 204, UserName = "user274", CommentBody = "[user274 comment's about author14 post's]", PostId = 28, PostRating = 2},
                new Comment(){ Id = 205, UserName = "user539", CommentBody = "[user539 comment's about author14 post's]", PostId = 28, PostRating = 7},
                new Comment(){ Id = 206, UserName = "user197", CommentBody = "[user197 comment's about author14 post's]", PostId = 28, PostRating = 8},
                new Comment(){ Id = 207, UserName = "user53", CommentBody = "[user53 comment's about author28 post's]", PostId = 29, PostRating = 1},
                new Comment(){ Id = 208, UserName = "user584", CommentBody = "[user584 comment's about author28 post's]", PostId = 29, PostRating = 6},
                new Comment(){ Id = 209, UserName = "user583", CommentBody = "[user583 comment's about author28 post's]", PostId = 29, PostRating = 8},
                new Comment(){ Id = 210, UserName = "user369", CommentBody = "[user369 comment's about author28 post's]", PostId = 29, PostRating = 1},
                new Comment(){ Id = 211, UserName = "user104", CommentBody = "[user104 comment's about author28 post's]", PostId = 29, PostRating = 7},
                new Comment(){ Id = 212, UserName = "user686", CommentBody = "[user686 comment's about author28 post's]", PostId = 29, PostRating = 5},
                new Comment(){ Id = 213, UserName = "user580", CommentBody = "[user580 comment's about author28 post's]", PostId = 29, PostRating = 3},
                new Comment(){ Id = 214, UserName = "user273", CommentBody = "[user273 comment's about author28 post's]", PostId = 29, PostRating = 4},
                new Comment(){ Id = 215, UserName = "user675", CommentBody = "[user675 comment's about author29 post's]", PostId = 30, PostRating = 5},
                new Comment(){ Id = 216, UserName = "user573", CommentBody = "[user573 comment's about author29 post's]", PostId = 30, PostRating = 8},
                new Comment(){ Id = 217, UserName = "user456", CommentBody = "[user456 comment's about author29 post's]", PostId = 30, PostRating = 9},
                new Comment(){ Id = 218, UserName = "user90", CommentBody = "[user90 comment's about author29 post's]", PostId = 30, PostRating = 3},
                new Comment(){ Id = 219, UserName = "user290", CommentBody = "[user290 comment's about author29 post's]", PostId = 30, PostRating = 9},
                new Comment(){ Id = 220, UserName = "user507", CommentBody = "[user507 comment's about author21 post's]", PostId = 31, PostRating = 4},
                new Comment(){ Id = 221, UserName = "user454", CommentBody = "[user454 comment's about author21 post's]", PostId = 31, PostRating = 1},
                new Comment(){ Id = 222, UserName = "user313", CommentBody = "[user313 comment's about author21 post's]", PostId = 31, PostRating = 6},
                new Comment(){ Id = 223, UserName = "user481", CommentBody = "[user481 comment's about author21 post's]", PostId = 31, PostRating = 5},
                new Comment(){ Id = 224, UserName = "user290", CommentBody = "[user290 comment's about author21 post's]", PostId = 31, PostRating = 2},
                new Comment(){ Id = 225, UserName = "user603", CommentBody = "[user603 comment's about author21 post's]", PostId = 31, PostRating = 8},
                new Comment(){ Id = 226, UserName = "user222", CommentBody = "[user222 comment's about author21 post's]", PostId = 31, PostRating = 5},
                new Comment(){ Id = 227, UserName = "user120", CommentBody = "[user120 comment's about author21 post's]", PostId = 31, PostRating = 9},
                new Comment(){ Id = 228, UserName = "user362", CommentBody = "[user362 comment's about author21 post's]", PostId = 31, PostRating = 5},
                new Comment(){ Id = 229, UserName = "user615", CommentBody = "[user615 comment's about author21 post's]", PostId = 31, PostRating = 6},
                new Comment(){ Id = 230, UserName = "user91", CommentBody = "[user91 comment's about author20 post's]", PostId = 32, PostRating = 7},
                new Comment(){ Id = 231, UserName = "user586", CommentBody = "[user586 comment's about author20 post's]", PostId = 32, PostRating = 5},
                new Comment(){ Id = 232, UserName = "user319", CommentBody = "[user319 comment's about author20 post's]", PostId = 32, PostRating = 6},
                new Comment(){ Id = 233, UserName = "user214", CommentBody = "[user214 comment's about author20 post's]", PostId = 32, PostRating = 9},
                new Comment(){ Id = 234, UserName = "user672", CommentBody = "[user672 comment's about author20 post's]", PostId = 32, PostRating = 2},
                new Comment(){ Id = 235, UserName = "user130", CommentBody = "[user130 comment's about author20 post's]", PostId = 32, PostRating = 2},
                new Comment(){ Id = 236, UserName = "user254", CommentBody = "[user254 comment's about author20 post's]", PostId = 32, PostRating = 1},
                new Comment(){ Id = 237, UserName = "user436", CommentBody = "[user436 comment's about author20 post's]", PostId = 32, PostRating = 4},
                new Comment(){ Id = 238, UserName = "user141", CommentBody = "[user141 comment's about author20 post's]", PostId = 32, PostRating = 6},
                new Comment(){ Id = 239, UserName = "user595", CommentBody = "[user595 comment's about author16 post's]", PostId = 33, PostRating = 3},
                new Comment(){ Id = 240, UserName = "user139", CommentBody = "[user139 comment's about author16 post's]", PostId = 33, PostRating = 9},
                new Comment(){ Id = 241, UserName = "user69", CommentBody = "[user69 comment's about author16 post's]", PostId = 33, PostRating = 4},
                new Comment(){ Id = 242, UserName = "user81", CommentBody = "[user81 comment's about author16 post's]", PostId = 33, PostRating = 2},
                new Comment(){ Id = 243, UserName = "user504", CommentBody = "[user504 comment's about author16 post's]", PostId = 33, PostRating = 5},
                new Comment(){ Id = 244, UserName = "user405", CommentBody = "[user405 comment's about author16 post's]", PostId = 33, PostRating = 4},
                new Comment(){ Id = 245, UserName = "user381", CommentBody = "[user381 comment's about author14 post's]", PostId = 34, PostRating = 8},
                new Comment(){ Id = 246, UserName = "user290", CommentBody = "[user290 comment's about author14 post's]", PostId = 34, PostRating = 7},
                new Comment(){ Id = 247, UserName = "user620", CommentBody = "[user620 comment's about author14 post's]", PostId = 34, PostRating = 1},
                new Comment(){ Id = 248, UserName = "user471", CommentBody = "[user471 comment's about author14 post's]", PostId = 34, PostRating = 6},
                new Comment(){ Id = 249, UserName = "user145", CommentBody = "[user145 comment's about author14 post's]", PostId = 34, PostRating = 9},
                new Comment(){ Id = 250, UserName = "user689", CommentBody = "[user689 comment's about author14 post's]", PostId = 34, PostRating = 7},
                new Comment(){ Id = 251, UserName = "user153", CommentBody = "[user153 comment's about author14 post's]", PostId = 34, PostRating = 4},
                new Comment(){ Id = 252, UserName = "user614", CommentBody = "[user614 comment's about author28 post's]", PostId = 35, PostRating = 8},
                new Comment(){ Id = 253, UserName = "user550", CommentBody = "[user550 comment's about author28 post's]", PostId = 35, PostRating = 4},
                new Comment(){ Id = 254, UserName = "user211", CommentBody = "[user211 comment's about author28 post's]", PostId = 35, PostRating = 2},
                new Comment(){ Id = 255, UserName = "user573", CommentBody = "[user573 comment's about author28 post's]", PostId = 35, PostRating = 8},
                new Comment(){ Id = 256, UserName = "user402", CommentBody = "[user402 comment's about author28 post's]", PostId = 35, PostRating = 1},
                new Comment(){ Id = 257, UserName = "user401", CommentBody = "[user401 comment's about author28 post's]", PostId = 35, PostRating = 1},
                new Comment(){ Id = 258, UserName = "user271", CommentBody = "[user271 comment's about author15 post's]", PostId = 36, PostRating = 3},
                new Comment(){ Id = 259, UserName = "user322", CommentBody = "[user322 comment's about author15 post's]", PostId = 36, PostRating = 1},
                new Comment(){ Id = 260, UserName = "user349", CommentBody = "[user349 comment's about author15 post's]", PostId = 36, PostRating = 2},
                new Comment(){ Id = 261, UserName = "user196", CommentBody = "[user196 comment's about author15 post's]", PostId = 36, PostRating = 1},
                new Comment(){ Id = 262, UserName = "user597", CommentBody = "[user597 comment's about author15 post's]", PostId = 36, PostRating = 8},
                new Comment(){ Id = 263, UserName = "user217", CommentBody = "[user217 comment's about author15 post's]", PostId = 36, PostRating = 5},
                new Comment(){ Id = 264, UserName = "user276", CommentBody = "[user276 comment's about author11 post's]", PostId = 37, PostRating = 3},
                new Comment(){ Id = 265, UserName = "user250", CommentBody = "[user250 comment's about author11 post's]", PostId = 37, PostRating = 8},
                new Comment(){ Id = 266, UserName = "user146", CommentBody = "[user146 comment's about author11 post's]", PostId = 37, PostRating = 8},
                new Comment(){ Id = 267, UserName = "user642", CommentBody = "[user642 comment's about author11 post's]", PostId = 37, PostRating = 3},
                new Comment(){ Id = 268, UserName = "user406", CommentBody = "[user406 comment's about author11 post's]", PostId = 37, PostRating = 7},
                new Comment(){ Id = 269, UserName = "user654", CommentBody = "[user654 comment's about author11 post's]", PostId = 37, PostRating = 4},
                new Comment(){ Id = 270, UserName = "user492", CommentBody = "[user492 comment's about author11 post's]", PostId = 37, PostRating = 4},
                new Comment(){ Id = 271, UserName = "user407", CommentBody = "[user407 comment's about author19 post's]", PostId = 38, PostRating = 7},
                new Comment(){ Id = 272, UserName = "user466", CommentBody = "[user466 comment's about author19 post's]", PostId = 38, PostRating = 4},
                new Comment(){ Id = 273, UserName = "user262", CommentBody = "[user262 comment's about author19 post's]", PostId = 38, PostRating = 7},
                new Comment(){ Id = 274, UserName = "user681", CommentBody = "[user681 comment's about author19 post's]", PostId = 38, PostRating = 1},
                new Comment(){ Id = 275, UserName = "user571", CommentBody = "[user571 comment's about author19 post's]", PostId = 38, PostRating = 2},
                new Comment(){ Id = 276, UserName = "user684", CommentBody = "[user684 comment's about author19 post's]", PostId = 38, PostRating = 7},
                new Comment(){ Id = 277, UserName = "user104", CommentBody = "[user104 comment's about author4 post's]", PostId = 39, PostRating = 8},
                new Comment(){ Id = 278, UserName = "user489", CommentBody = "[user489 comment's about author4 post's]", PostId = 39, PostRating = 1},
                new Comment(){ Id = 279, UserName = "user233", CommentBody = "[user233 comment's about author4 post's]", PostId = 39, PostRating = 8},
                new Comment(){ Id = 280, UserName = "user480", CommentBody = "[user480 comment's about author4 post's]", PostId = 39, PostRating = 4},
                new Comment(){ Id = 281, UserName = "user525", CommentBody = "[user525 comment's about author8 post's]", PostId = 40, PostRating = 7},
                new Comment(){ Id = 282, UserName = "user566", CommentBody = "[user566 comment's about author8 post's]", PostId = 40, PostRating = 3},
                new Comment(){ Id = 283, UserName = "user249", CommentBody = "[user249 comment's about author8 post's]", PostId = 40, PostRating = 7},
                new Comment(){ Id = 284, UserName = "user149", CommentBody = "[user149 comment's about author8 post's]", PostId = 40, PostRating = 1},
                new Comment(){ Id = 285, UserName = "user367", CommentBody = "[user367 comment's about author8 post's]", PostId = 40, PostRating = 5},
                new Comment(){ Id = 286, UserName = "user361", CommentBody = "[user361 comment's about author8 post's]", PostId = 40, PostRating = 8},
                new Comment(){ Id = 287, UserName = "user463", CommentBody = "[user463 comment's about author8 post's]", PostId = 40, PostRating = 9},
                new Comment(){ Id = 288, UserName = "user297", CommentBody = "[user297 comment's about author21 post's]", PostId = 41, PostRating = 3},
                new Comment(){ Id = 289, UserName = "user599", CommentBody = "[user599 comment's about author21 post's]", PostId = 41, PostRating = 7},
                new Comment(){ Id = 290, UserName = "user358", CommentBody = "[user358 comment's about author21 post's]", PostId = 41, PostRating = 6},
                new Comment(){ Id = 291, UserName = "user287", CommentBody = "[user287 comment's about author21 post's]", PostId = 41, PostRating = 4},
                new Comment(){ Id = 292, UserName = "user402", CommentBody = "[user402 comment's about author21 post's]", PostId = 41, PostRating = 9},
                new Comment(){ Id = 293, UserName = "user420", CommentBody = "[user420 comment's about author21 post's]", PostId = 41, PostRating = 8},
                new Comment(){ Id = 294, UserName = "user143", CommentBody = "[user143 comment's about author27 post's]", PostId = 42, PostRating = 2},
                new Comment(){ Id = 295, UserName = "user196", CommentBody = "[user196 comment's about author27 post's]", PostId = 42, PostRating = 9},
                new Comment(){ Id = 296, UserName = "user309", CommentBody = "[user309 comment's about author27 post's]", PostId = 42, PostRating = 1},
                new Comment(){ Id = 297, UserName = "user368", CommentBody = "[user368 comment's about author18 post's]", PostId = 43, PostRating = 9},
                new Comment(){ Id = 298, UserName = "user650", CommentBody = "[user650 comment's about author18 post's]", PostId = 43, PostRating = 3},
                new Comment(){ Id = 299, UserName = "user539", CommentBody = "[user539 comment's about author18 post's]", PostId = 43, PostRating = 8},
                new Comment(){ Id = 300, UserName = "user158", CommentBody = "[user158 comment's about author18 post's]", PostId = 43, PostRating = 1},
                new Comment(){ Id = 301, UserName = "user289", CommentBody = "[user289 comment's about author18 post's]", PostId = 43, PostRating = 3},
                new Comment(){ Id = 302, UserName = "user165", CommentBody = "[user165 comment's about author18 post's]", PostId = 43, PostRating = 7},
                new Comment(){ Id = 303, UserName = "user242", CommentBody = "[user242 comment's about author16 post's]", PostId = 44, PostRating = 9},
                new Comment(){ Id = 304, UserName = "user648", CommentBody = "[user648 comment's about author16 post's]", PostId = 44, PostRating = 9},
                new Comment(){ Id = 305, UserName = "user385", CommentBody = "[user385 comment's about author16 post's]", PostId = 44, PostRating = 4},
                new Comment(){ Id = 306, UserName = "user320", CommentBody = "[user320 comment's about author16 post's]", PostId = 44, PostRating = 2},
                new Comment(){ Id = 307, UserName = "user464", CommentBody = "[user464 comment's about author25 post's]", PostId = 45, PostRating = 7},
                new Comment(){ Id = 308, UserName = "user372", CommentBody = "[user372 comment's about author25 post's]", PostId = 45, PostRating = 9},
                new Comment(){ Id = 309, UserName = "user602", CommentBody = "[user602 comment's about author25 post's]", PostId = 45, PostRating = 9},
                new Comment(){ Id = 310, UserName = "user166", CommentBody = "[user166 comment's about author25 post's]", PostId = 45, PostRating = 1},
                new Comment(){ Id = 311, UserName = "user270", CommentBody = "[user270 comment's about author25 post's]", PostId = 45, PostRating = 4},
                new Comment(){ Id = 312, UserName = "user586", CommentBody = "[user586 comment's about author25 post's]", PostId = 45, PostRating = 9},
                new Comment(){ Id = 313, UserName = "user439", CommentBody = "[user439 comment's about author25 post's]", PostId = 45, PostRating = 9},
                new Comment(){ Id = 314, UserName = "user278", CommentBody = "[user278 comment's about author25 post's]", PostId = 45, PostRating = 6},
                new Comment(){ Id = 315, UserName = "user279", CommentBody = "[user279 comment's about author25 post's]", PostId = 45, PostRating = 8},
                new Comment(){ Id = 316, UserName = "user500", CommentBody = "[user500 comment's about author18 post's]", PostId = 46, PostRating = 2},
                new Comment(){ Id = 317, UserName = "user423", CommentBody = "[user423 comment's about author18 post's]", PostId = 46, PostRating = 7},
                new Comment(){ Id = 318, UserName = "user388", CommentBody = "[user388 comment's about author18 post's]", PostId = 46, PostRating = 2},
                new Comment(){ Id = 319, UserName = "user132", CommentBody = "[user132 comment's about author18 post's]", PostId = 46, PostRating = 6},
                new Comment(){ Id = 320, UserName = "user569", CommentBody = "[user569 comment's about author18 post's]", PostId = 46, PostRating = 2},
                new Comment(){ Id = 321, UserName = "user59", CommentBody = "[user59 comment's about author18 post's]", PostId = 46, PostRating = 4},
                new Comment(){ Id = 322, UserName = "user278", CommentBody = "[user278 comment's about author18 post's]", PostId = 46, PostRating = 1},
                new Comment(){ Id = 323, UserName = "user98", CommentBody = "[user98 comment's about author18 post's]", PostId = 46, PostRating = 1},
                new Comment(){ Id = 324, UserName = "user235", CommentBody = "[user235 comment's about author18 post's]", PostId = 46, PostRating = 2},
                new Comment(){ Id = 325, UserName = "user143", CommentBody = "[user143 comment's about author18 post's]", PostId = 46, PostRating = 2},
                new Comment(){ Id = 326, UserName = "user211", CommentBody = "[user211 comment's about author18 post's]", PostId = 46, PostRating = 7},
                new Comment(){ Id = 327, UserName = "user583", CommentBody = "[user583 comment's about author21 post's]", PostId = 47, PostRating = 7},
                new Comment(){ Id = 328, UserName = "user306", CommentBody = "[user306 comment's about author21 post's]", PostId = 47, PostRating = 2},
                new Comment(){ Id = 329, UserName = "user562", CommentBody = "[user562 comment's about author21 post's]", PostId = 47, PostRating = 8},
                new Comment(){ Id = 330, UserName = "user59", CommentBody = "[user59 comment's about author24 post's]", PostId = 48, PostRating = 7},
                new Comment(){ Id = 331, UserName = "user232", CommentBody = "[user232 comment's about author24 post's]", PostId = 48, PostRating = 1},
                new Comment(){ Id = 332, UserName = "user148", CommentBody = "[user148 comment's about author24 post's]", PostId = 48, PostRating = 8},
                new Comment(){ Id = 333, UserName = "user464", CommentBody = "[user464 comment's about author24 post's]", PostId = 48, PostRating = 7},
                new Comment(){ Id = 334, UserName = "user84", CommentBody = "[user84 comment's about author24 post's]", PostId = 48, PostRating = 8},
                new Comment(){ Id = 335, UserName = "user594", CommentBody = "[user594 comment's about author24 post's]", PostId = 48, PostRating = 1},
                new Comment(){ Id = 336, UserName = "user155", CommentBody = "[user155 comment's about author26 post's]", PostId = 49, PostRating = 9},
                new Comment(){ Id = 337, UserName = "user232", CommentBody = "[user232 comment's about author26 post's]", PostId = 49, PostRating = 8},
                new Comment(){ Id = 338, UserName = "user579", CommentBody = "[user579 comment's about author26 post's]", PostId = 49, PostRating = 3},
                new Comment(){ Id = 339, UserName = "user259", CommentBody = "[user259 comment's about author26 post's]", PostId = 49, PostRating = 4},
                new Comment(){ Id = 340, UserName = "user400", CommentBody = "[user400 comment's about author26 post's]", PostId = 49, PostRating = 5},
                new Comment(){ Id = 341, UserName = "user661", CommentBody = "[user661 comment's about author26 post's]", PostId = 49, PostRating = 7},
                new Comment(){ Id = 342, UserName = "user419", CommentBody = "[user419 comment's about author26 post's]", PostId = 49, PostRating = 9},
                new Comment(){ Id = 343, UserName = "user116", CommentBody = "[user116 comment's about author26 post's]", PostId = 49, PostRating = 6},
                new Comment(){ Id = 344, UserName = "user642", CommentBody = "[user642 comment's about author4 post's]", PostId = 50, PostRating = 7},
                new Comment(){ Id = 345, UserName = "user631", CommentBody = "[user631 comment's about author4 post's]", PostId = 50, PostRating = 6},
                new Comment(){ Id = 346, UserName = "user398", CommentBody = "[user398 comment's about author4 post's]", PostId = 50, PostRating = 8},
                new Comment(){ Id = 347, UserName = "user531", CommentBody = "[user531 comment's about author4 post's]", PostId = 50, PostRating = 8},
                new Comment(){ Id = 348, UserName = "user86", CommentBody = "[user86 comment's about author4 post's]", PostId = 50, PostRating = 1},
                new Comment(){ Id = 349, UserName = "user346", CommentBody = "[user346 comment's about author4 post's]", PostId = 50, PostRating = 9},
                new Comment(){ Id = 350, UserName = "user214", CommentBody = "[user214 comment's about author4 post's]", PostId = 50, PostRating = 3},
                new Comment(){ Id = 351, UserName = "user158", CommentBody = "[user158 comment's about author4 post's]", PostId = 50, PostRating = 4},
                new Comment(){ Id = 352, UserName = "user234", CommentBody = "[user234 comment's about author9 post's]", PostId = 51, PostRating = 7},
                new Comment(){ Id = 353, UserName = "user285", CommentBody = "[user285 comment's about author9 post's]", PostId = 51, PostRating = 4},
                new Comment(){ Id = 354, UserName = "user279", CommentBody = "[user279 comment's about author9 post's]", PostId = 51, PostRating = 6},
                new Comment(){ Id = 355, UserName = "user365", CommentBody = "[user365 comment's about author9 post's]", PostId = 51, PostRating = 7},
                new Comment(){ Id = 356, UserName = "user651", CommentBody = "[user651 comment's about author1 post's]", PostId = 52, PostRating = 7},
                new Comment(){ Id = 357, UserName = "user380", CommentBody = "[user380 comment's about author1 post's]", PostId = 52, PostRating = 8},
                new Comment(){ Id = 358, UserName = "user63", CommentBody = "[user63 comment's about author1 post's]", PostId = 52, PostRating = 4},
                new Comment(){ Id = 359, UserName = "user426", CommentBody = "[user426 comment's about author1 post's]", PostId = 52, PostRating = 2},
                new Comment(){ Id = 360, UserName = "user227", CommentBody = "[user227 comment's about author1 post's]", PostId = 52, PostRating = 3},
                new Comment(){ Id = 361, UserName = "user238", CommentBody = "[user238 comment's about author1 post's]", PostId = 52, PostRating = 4},
                new Comment(){ Id = 362, UserName = "user431", CommentBody = "[user431 comment's about author1 post's]", PostId = 52, PostRating = 9},
                new Comment(){ Id = 363, UserName = "user331", CommentBody = "[user331 comment's about author1 post's]", PostId = 52, PostRating = 5},
                new Comment(){ Id = 364, UserName = "user82", CommentBody = "[user82 comment's about author20 post's]", PostId = 53, PostRating = 2},
                new Comment(){ Id = 365, UserName = "user583", CommentBody = "[user583 comment's about author20 post's]", PostId = 53, PostRating = 8},
                new Comment(){ Id = 366, UserName = "user194", CommentBody = "[user194 comment's about author20 post's]", PostId = 53, PostRating = 6},
                new Comment(){ Id = 367, UserName = "user387", CommentBody = "[user387 comment's about author20 post's]", PostId = 53, PostRating = 3},
                new Comment(){ Id = 368, UserName = "user477", CommentBody = "[user477 comment's about author19 post's]", PostId = 54, PostRating = 6},
                new Comment(){ Id = 369, UserName = "user440", CommentBody = "[user440 comment's about author19 post's]", PostId = 54, PostRating = 9},
                new Comment(){ Id = 370, UserName = "user474", CommentBody = "[user474 comment's about author19 post's]", PostId = 54, PostRating = 5},
                new Comment(){ Id = 371, UserName = "user333", CommentBody = "[user333 comment's about author19 post's]", PostId = 54, PostRating = 3},
                new Comment(){ Id = 372, UserName = "user152", CommentBody = "[user152 comment's about author19 post's]", PostId = 54, PostRating = 6},
                new Comment(){ Id = 373, UserName = "user84", CommentBody = "[user84 comment's about author19 post's]", PostId = 54, PostRating = 6},
                new Comment(){ Id = 374, UserName = "user265", CommentBody = "[user265 comment's about author19 post's]", PostId = 54, PostRating = 1},
                new Comment(){ Id = 375, UserName = "user687", CommentBody = "[user687 comment's about author9 post's]", PostId = 55, PostRating = 8},
                new Comment(){ Id = 376, UserName = "user175", CommentBody = "[user175 comment's about author9 post's]", PostId = 55, PostRating = 5},
                new Comment(){ Id = 377, UserName = "user588", CommentBody = "[user588 comment's about author9 post's]", PostId = 55, PostRating = 3},
                new Comment(){ Id = 378, UserName = "user446", CommentBody = "[user446 comment's about author9 post's]", PostId = 55, PostRating = 1},
                new Comment(){ Id = 379, UserName = "user678", CommentBody = "[user678 comment's about author9 post's]", PostId = 55, PostRating = 6},
                new Comment(){ Id = 380, UserName = "user387", CommentBody = "[user387 comment's about author9 post's]", PostId = 55, PostRating = 8},
                new Comment(){ Id = 381, UserName = "user296", CommentBody = "[user296 comment's about author9 post's]", PostId = 55, PostRating = 2},
                new Comment(){ Id = 382, UserName = "user347", CommentBody = "[user347 comment's about author9 post's]", PostId = 55, PostRating = 8},
                new Comment(){ Id = 383, UserName = "user199", CommentBody = "[user199 comment's about author9 post's]", PostId = 55, PostRating = 5},
                new Comment(){ Id = 384, UserName = "user491", CommentBody = "[user491 comment's about author13 post's]", PostId = 56, PostRating = 6},
                new Comment(){ Id = 385, UserName = "user641", CommentBody = "[user641 comment's about author13 post's]", PostId = 56, PostRating = 6},
                new Comment(){ Id = 386, UserName = "user272", CommentBody = "[user272 comment's about author13 post's]", PostId = 56, PostRating = 9},
                new Comment(){ Id = 387, UserName = "user377", CommentBody = "[user377 comment's about author13 post's]", PostId = 56, PostRating = 2},
                new Comment(){ Id = 388, UserName = "user689", CommentBody = "[user689 comment's about author13 post's]", PostId = 56, PostRating = 7},
                new Comment(){ Id = 389, UserName = "user475", CommentBody = "[user475 comment's about author13 post's]", PostId = 56, PostRating = 8},
                new Comment(){ Id = 390, UserName = "user385", CommentBody = "[user385 comment's about author13 post's]", PostId = 56, PostRating = 5},
                new Comment(){ Id = 391, UserName = "user407", CommentBody = "[user407 comment's about author13 post's]", PostId = 56, PostRating = 6},
                new Comment(){ Id = 392, UserName = "user63", CommentBody = "[user63 comment's about author16 post's]", PostId = 57, PostRating = 2},
                new Comment(){ Id = 393, UserName = "user151", CommentBody = "[user151 comment's about author16 post's]", PostId = 57, PostRating = 3},
                new Comment(){ Id = 394, UserName = "user299", CommentBody = "[user299 comment's about author16 post's]", PostId = 57, PostRating = 8},
                new Comment(){ Id = 395, UserName = "user512", CommentBody = "[user512 comment's about author16 post's]", PostId = 57, PostRating = 1},
                new Comment(){ Id = 396, UserName = "user336", CommentBody = "[user336 comment's about author16 post's]", PostId = 57, PostRating = 4},
                new Comment(){ Id = 397, UserName = "user490", CommentBody = "[user490 comment's about author16 post's]", PostId = 57, PostRating = 5},
                new Comment(){ Id = 398, UserName = "user215", CommentBody = "[user215 comment's about author26 post's]", PostId = 58, PostRating = 7},
                new Comment(){ Id = 399, UserName = "user78", CommentBody = "[user78 comment's about author26 post's]", PostId = 58, PostRating = 4},
                new Comment(){ Id = 400, UserName = "user693", CommentBody = "[user693 comment's about author26 post's]", PostId = 58, PostRating = 2},
                new Comment(){ Id = 401, UserName = "user422", CommentBody = "[user422 comment's about author26 post's]", PostId = 58, PostRating = 5},
                new Comment(){ Id = 402, UserName = "user682", CommentBody = "[user682 comment's about author26 post's]", PostId = 58, PostRating = 1},
                new Comment(){ Id = 403, UserName = "user585", CommentBody = "[user585 comment's about author2 post's]", PostId = 59, PostRating = 3},
                new Comment(){ Id = 404, UserName = "user458", CommentBody = "[user458 comment's about author2 post's]", PostId = 59, PostRating = 7},
                new Comment(){ Id = 405, UserName = "user461", CommentBody = "[user461 comment's about author2 post's]", PostId = 59, PostRating = 4},
                new Comment(){ Id = 406, UserName = "user583", CommentBody = "[user583 comment's about author2 post's]", PostId = 59, PostRating = 5},
                new Comment(){ Id = 407, UserName = "user257", CommentBody = "[user257 comment's about author2 post's]", PostId = 59, PostRating = 4},
                new Comment(){ Id = 408, UserName = "user611", CommentBody = "[user611 comment's about author2 post's]", PostId = 59, PostRating = 6},
                new Comment(){ Id = 409, UserName = "user171", CommentBody = "[user171 comment's about author2 post's]", PostId = 59, PostRating = 9},
                new Comment(){ Id = 410, UserName = "user221", CommentBody = "[user221 comment's about author25 post's]", PostId = 60, PostRating = 1},
                new Comment(){ Id = 411, UserName = "user146", CommentBody = "[user146 comment's about author25 post's]", PostId = 60, PostRating = 6},
                new Comment(){ Id = 412, UserName = "user616", CommentBody = "[user616 comment's about author25 post's]", PostId = 60, PostRating = 2},
                new Comment(){ Id = 413, UserName = "user538", CommentBody = "[user538 comment's about author25 post's]", PostId = 60, PostRating = 6}
            };


            modelBuilder.Entity<Blog>().HasData(blogs);
            modelBuilder.Entity<Post>().HasData(posts);
            modelBuilder.Entity<Comment>().HasData(comments);
        }
    }
}
